# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget ROOT::vectorDict ROOT::listDict ROOT::forward_listDict ROOT::dequeDict ROOT::mapDict ROOT::map2Dict ROOT::unordered_mapDict ROOT::multimapDict ROOT::multimap2Dict ROOT::unordered_multimapDict ROOT::setDict ROOT::unordered_setDict ROOT::multisetDict ROOT::unordered_multisetDict ROOT::complexDict ROOT::valarrayDict ROOT::Cling ROOT::MultiProc ROOT::Rint ROOT::Thread ROOT::Imt ROOT::New ROOT::rootcling_stage1 ROOT::Core ROOT::rmkdepend ROOT::MathCore ROOT::MathMore ROOT::Matrix ROOT::Minuit ROOT::Minuit2 ROOT::Fumili ROOT::Physics ROOT::MLP ROOT::Quadp ROOT::Foam ROOT::Smatrix ROOT::SPlot ROOT::GenVector ROOT::Genetic ROOT::FFTW ROOT::ROOTVecOps ROOT::Hist ROOT::HistPainter ROOT::Spectrum ROOT::SpectrumPainter ROOT::Unfold ROOT::Tree ROOT::TreePlayer ROOT::TreeViewer ROOT::ROOTDataFrame ROOT::RIO ROOT::SQLIO ROOT::XMLIO ROOT::XMLParser ROOT::Net ROOT::RootAuth ROOT::SrvAuth ROOT::NetxNG ROOT::RHTTP ROOT::RHTTPSniff ROOT::Gpad ROOT::Graf ROOT::Postscript ROOT::mathtext ROOT::GX11 ROOT::GX11TTF ROOT::ASImage ROOT::ASImageGui ROOT::FITSIO ROOT::Graf3d ROOT::X3d ROOT::RCsg ROOT::Eve ROOT::RGL ROOT::Gviz3d ROOT::Gui ROOT::Ged ROOT::FitPanel ROOT::GuiBld ROOT::GuiHtml ROOT::Recorder ROOT::SessionViewer ROOT::Proof ROOT::ProofPlayer ROOT::ProofDraw ROOT::ProofBench ROOT::Html ROOT::EG ROOT::Geom ROOT::GeomBuilder ROOT::GeomPainter ROOT::Gdml ROOT::root ROOT::rootn.exe ROOT::roots.exe ROOT::xpdtest ROOT::root.exe ROOT::proofserv.exe ROOT::hadd ROOT::rootnb.exe ROOT::rootcling ROOT::cppyy_backend3_7 ROOT::cppyy_backend2_7 ROOT::cppyy3_7 ROOT::cppyy2_7 ROOT::ROOTTPython ROOT::RMySQL ROOT::TMVA ROOT::TMVAGui ROOT::ROOTTMVASofie ROOT::RooBatchCompute ROOT::RooBatchCompute_GENERIC ROOT::RooBatchCompute_SSE4.1 ROOT::RooBatchCompute_AVX ROOT::RooBatchCompute_AVX2 ROOT::RooBatchCompute_AVX512 ROOT::RooFitCommon ROOT::RooFitCore ROOT::RooFit ROOT::RooFitMore ROOT::RooStats ROOT::HistFactory ROOT::hist2workspace ROOT::RooFitRDataFrameHelpers ROOT::RooFitHS3)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target ROOT::vectorDict
add_library(ROOT::vectorDict SHARED IMPORTED)

set_target_properties(ROOT::vectorDict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::listDict
add_library(ROOT::listDict SHARED IMPORTED)

set_target_properties(ROOT::listDict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::forward_listDict
add_library(ROOT::forward_listDict SHARED IMPORTED)

set_target_properties(ROOT::forward_listDict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::dequeDict
add_library(ROOT::dequeDict SHARED IMPORTED)

set_target_properties(ROOT::dequeDict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::mapDict
add_library(ROOT::mapDict SHARED IMPORTED)

set_target_properties(ROOT::mapDict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::map2Dict
add_library(ROOT::map2Dict SHARED IMPORTED)

set_target_properties(ROOT::map2Dict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::unordered_mapDict
add_library(ROOT::unordered_mapDict SHARED IMPORTED)

set_target_properties(ROOT::unordered_mapDict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::multimapDict
add_library(ROOT::multimapDict SHARED IMPORTED)

set_target_properties(ROOT::multimapDict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::multimap2Dict
add_library(ROOT::multimap2Dict SHARED IMPORTED)

set_target_properties(ROOT::multimap2Dict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::unordered_multimapDict
add_library(ROOT::unordered_multimapDict SHARED IMPORTED)

set_target_properties(ROOT::unordered_multimapDict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::setDict
add_library(ROOT::setDict SHARED IMPORTED)

set_target_properties(ROOT::setDict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::unordered_setDict
add_library(ROOT::unordered_setDict SHARED IMPORTED)

set_target_properties(ROOT::unordered_setDict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::multisetDict
add_library(ROOT::multisetDict SHARED IMPORTED)

set_target_properties(ROOT::multisetDict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::unordered_multisetDict
add_library(ROOT::unordered_multisetDict SHARED IMPORTED)

set_target_properties(ROOT::unordered_multisetDict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::complexDict
add_library(ROOT::complexDict SHARED IMPORTED)

set_target_properties(ROOT::complexDict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::valarrayDict
add_library(ROOT::valarrayDict SHARED IMPORTED)

set_target_properties(ROOT::valarrayDict PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/clingutils/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::Cling
add_library(ROOT::Cling SHARED IMPORTED)

set_target_properties(ROOT::Cling PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_LINK_LIBRARIES "-Wl,--unresolved-symbols=ignore-in-object-files"
)

# Create imported target ROOT::MultiProc
add_library(ROOT::MultiProc SHARED IMPORTED)

set_target_properties(ROOT::MultiProc PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/multiproc/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::Net"
)

# Create imported target ROOT::Rint
add_library(ROOT::Rint SHARED IMPORTED)

set_target_properties(ROOT::Rint PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/rint/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::Thread
add_library(ROOT::Thread SHARED IMPORTED)

set_target_properties(ROOT::Thread PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/thread/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;-lpthread"
)

# Create imported target ROOT::Imt
add_library(ROOT::Imt SHARED IMPORTED)

set_target_properties(ROOT::Imt PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/core/imt/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::MultiProc;ROOT::Core"
)

# Create imported target ROOT::New
add_library(ROOT::New SHARED IMPORTED)

set_target_properties(ROOT::New PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::rootcling_stage1
add_executable(ROOT::rootcling_stage1 IMPORTED)

# Create imported target ROOT::Core
add_library(ROOT::Core SHARED IMPORTED)

set_target_properties(ROOT::Core PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_build/ginclude;/home/nicobigio01/colab_root/root_src/core/base/inc;/home/nicobigio01/colab_root/root_src/core/foundation/inc;/home/nicobigio01/colab_root/root_src/core/cont/inc;/home/nicobigio01/colab_root/root_src/core/gui/inc;/home/nicobigio01/colab_root/root_src/core/meta/inc;/home/nicobigio01/colab_root/root_src/core/clib/inc;/home/nicobigio01/colab_root/root_src/core/rint/inc;/home/nicobigio01/colab_root/root_src/core/zip/inc;/home/nicobigio01/colab_root/root_src/core/thread/inc;/home/nicobigio01/colab_root/root_src/core/textinput/inc;/home/nicobigio01/colab_root/root_src/core/base/v7/inc;/home/nicobigio01/colab_root/root_src/core/foundation/v7/inc;/home/nicobigio01/colab_root/root_src/core/unix/inc"
)

# Create imported target ROOT::rmkdepend
add_executable(ROOT::rmkdepend IMPORTED)

# Create imported target ROOT::MathCore
add_library(ROOT::MathCore SHARED IMPORTED)

set_target_properties(ROOT::MathCore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/mathcore/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::Imt"
)

# Create imported target ROOT::MathMore
add_library(ROOT::MathMore SHARED IMPORTED)

set_target_properties(ROOT::MathMore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/mathmore/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::MathCore"
)

# Create imported target ROOT::Matrix
add_library(ROOT::Matrix SHARED IMPORTED)

set_target_properties(ROOT::Matrix PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/matrix/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::MathCore"
)

# Create imported target ROOT::Minuit
add_library(ROOT::Minuit SHARED IMPORTED)

set_target_properties(ROOT::Minuit PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/minuit/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Graf;ROOT::Hist;ROOT::Matrix;ROOT::MathCore"
)

# Create imported target ROOT::Minuit2
add_library(ROOT::Minuit2 SHARED IMPORTED)

set_target_properties(ROOT::Minuit2 PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/minuit2/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::MathCore;ROOT::Hist"
)

# Create imported target ROOT::Fumili
add_library(ROOT::Fumili SHARED IMPORTED)

set_target_properties(ROOT::Fumili PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/fumili/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Graf;ROOT::Hist;ROOT::MathCore"
)

# Create imported target ROOT::Physics
add_library(ROOT::Physics SHARED IMPORTED)

set_target_properties(ROOT::Physics PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/physics/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Matrix;ROOT::MathCore"
)

# Create imported target ROOT::MLP
add_library(ROOT::MLP SHARED IMPORTED)

set_target_properties(ROOT::MLP PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/mlp/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Hist;ROOT::Matrix;ROOT::Tree;ROOT::Graf;ROOT::Gpad;ROOT::TreePlayer;ROOT::MathCore"
)

# Create imported target ROOT::Quadp
add_library(ROOT::Quadp SHARED IMPORTED)

set_target_properties(ROOT::Quadp PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/quadp/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Matrix"
)

# Create imported target ROOT::Foam
add_library(ROOT::Foam SHARED IMPORTED)

set_target_properties(ROOT::Foam PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/foam/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Hist;ROOT::MathCore"
)

# Create imported target ROOT::Smatrix
add_library(ROOT::Smatrix SHARED IMPORTED)

set_target_properties(ROOT::Smatrix PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/smatrix/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::MathCore"
)

# Create imported target ROOT::SPlot
add_library(ROOT::SPlot SHARED IMPORTED)

set_target_properties(ROOT::SPlot PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/splot/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Matrix;ROOT::Hist;ROOT::Tree;ROOT::TreePlayer;ROOT::Graf3d;ROOT::Graf;ROOT::MathCore"
)

# Create imported target ROOT::GenVector
add_library(ROOT::GenVector SHARED IMPORTED)

set_target_properties(ROOT::GenVector PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/genvector/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::MathCore"
)

# Create imported target ROOT::Genetic
add_library(ROOT::Genetic SHARED IMPORTED)

set_target_properties(ROOT::Genetic PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/genetic/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::MathCore;ROOT::TMVA"
)

# Create imported target ROOT::FFTW
add_library(ROOT::FFTW SHARED IMPORTED)

set_target_properties(ROOT::FFTW PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/fftw/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::MathCore"
)

# Create imported target ROOT::ROOTVecOps
add_library(ROOT::ROOTVecOps SHARED IMPORTED)

set_target_properties(ROOT::ROOTVecOps PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/math/vecops/inc;/home/nicobigio01/colab_root/root_build/ginclude"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::Hist
add_library(ROOT::Hist SHARED IMPORTED)

set_target_properties(ROOT::Hist PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/hist/hist/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::MathCore;ROOT::Matrix;ROOT::RIO"
)

# Create imported target ROOT::HistPainter
add_library(ROOT::HistPainter SHARED IMPORTED)

set_target_properties(ROOT::HistPainter PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/hist/histpainter/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Gpad;ROOT::Graf;ROOT::Hist;ROOT::MathCore;ROOT::Matrix"
)

# Create imported target ROOT::Spectrum
add_library(ROOT::Spectrum SHARED IMPORTED)

set_target_properties(ROOT::Spectrum PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/hist/spectrum/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Hist;ROOT::Matrix"
)

# Create imported target ROOT::SpectrumPainter
add_library(ROOT::SpectrumPainter SHARED IMPORTED)

set_target_properties(ROOT::SpectrumPainter PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/hist/spectrumpainter/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Graf;ROOT::Hist;ROOT::Gpad"
)

# Create imported target ROOT::Unfold
add_library(ROOT::Unfold SHARED IMPORTED)

set_target_properties(ROOT::Unfold PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/hist/unfold/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Hist;ROOT::XMLParser;ROOT::Matrix"
)

# Create imported target ROOT::Tree
add_library(ROOT::Tree SHARED IMPORTED)

set_target_properties(ROOT::Tree PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/tree/tree/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Imt;ROOT::Net;ROOT::RIO;ROOT::MathCore"
)

# Create imported target ROOT::TreePlayer
add_library(ROOT::TreePlayer SHARED IMPORTED)

set_target_properties(ROOT::TreePlayer PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/tree/treeplayer/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Gpad;ROOT::Graf;ROOT::Graf3d;ROOT::Hist;ROOT::Imt;ROOT::MathCore;ROOT::RIO;ROOT::Tree;ROOT::MultiProc"
)

# Create imported target ROOT::TreeViewer
add_library(ROOT::TreeViewer SHARED IMPORTED)

set_target_properties(ROOT::TreeViewer PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/tree/treeviewer/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Ged;ROOT::Gui;ROOT::TreePlayer"
)

# Create imported target ROOT::ROOTDataFrame
add_library(ROOT::ROOTDataFrame SHARED IMPORTED)

set_target_properties(ROOT::ROOTDataFrame PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/tree/dataframe/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Tree;ROOT::TreePlayer;ROOT::Hist;ROOT::RIO;ROOT::ROOTVecOps;ROOT::Imt"
)

# Create imported target ROOT::RIO
add_library(ROOT::RIO SHARED IMPORTED)

set_target_properties(ROOT::RIO PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/io/io/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::Thread"
)

# Create imported target ROOT::SQLIO
add_library(ROOT::SQLIO SHARED IMPORTED)

set_target_properties(ROOT::SQLIO PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/io/sql/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Net;ROOT::RIO"
)

# Create imported target ROOT::XMLIO
add_library(ROOT::XMLIO SHARED IMPORTED)

set_target_properties(ROOT::XMLIO PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/io/xml/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::RIO"
)

# Create imported target ROOT::XMLParser
add_library(ROOT::XMLParser SHARED IMPORTED)

set_target_properties(ROOT::XMLParser PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/io/xmlparser/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::Net
add_library(ROOT::Net SHARED IMPORTED)

set_target_properties(ROOT::Net PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/net/net/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::RIO"
)

# Create imported target ROOT::RootAuth
add_library(ROOT::RootAuth SHARED IMPORTED)

set_target_properties(ROOT::RootAuth PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/net/auth/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Net;ROOT::RIO"
)

# Create imported target ROOT::SrvAuth
add_library(ROOT::SrvAuth SHARED IMPORTED)

set_target_properties(ROOT::SrvAuth PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_LINK_LIBRARIES "ROOT::Net"
)

# Create imported target ROOT::NetxNG
add_library(ROOT::NetxNG SHARED IMPORTED)

set_target_properties(ROOT::NetxNG PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/net/netxng/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Net;ROOT::RIO;ROOT::Thread"
)

# Create imported target ROOT::RHTTP
add_library(ROOT::RHTTP SHARED IMPORTED)

set_target_properties(ROOT::RHTTP PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "USE_WEBSOCKET;NO_SSL_DL;HTTP_WITHOUT_FASTCGI"
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/net/http/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::RIO;ROOT::Thread;ROOT::Graf"
)

# Create imported target ROOT::RHTTPSniff
add_library(ROOT::RHTTPSniff SHARED IMPORTED)

set_target_properties(ROOT::RHTTPSniff PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/net/httpsniff/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Gpad;ROOT::Graf;ROOT::Hist;ROOT::RHTTP;ROOT::RIO;ROOT::Thread;ROOT::Tree;ROOT::XMLIO"
)

# Create imported target ROOT::Gpad
add_library(ROOT::Gpad SHARED IMPORTED)

set_target_properties(ROOT::Gpad PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf2d/gpad/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Graf;ROOT::Hist"
)

# Create imported target ROOT::Graf
add_library(ROOT::Graf SHARED IMPORTED)

set_target_properties(ROOT::Graf PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf2d/graf/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Hist;ROOT::Matrix;ROOT::MathCore;ROOT::RIO"
)

# Create imported target ROOT::Postscript
add_library(ROOT::Postscript SHARED IMPORTED)

set_target_properties(ROOT::Postscript PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf2d/postscript/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Graf"
)

# Create imported target ROOT::mathtext
add_library(ROOT::mathtext STATIC IMPORTED)

set_target_properties(ROOT::mathtext PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf2d/mathtext/inc"
)

# Create imported target ROOT::GX11
add_library(ROOT::GX11 SHARED IMPORTED)

set_target_properties(ROOT::GX11 PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf2d/x11/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::MathCore"
)

# Create imported target ROOT::GX11TTF
add_library(ROOT::GX11TTF SHARED IMPORTED)

set_target_properties(ROOT::GX11TTF PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf2d/x11ttf/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::GX11;ROOT::Graf"
)

# Create imported target ROOT::ASImage
add_library(ROOT::ASImage SHARED IMPORTED)

set_target_properties(ROOT::ASImage PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf2d/asimage/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::Graf"
)

# Create imported target ROOT::ASImageGui
add_library(ROOT::ASImageGui SHARED IMPORTED)

set_target_properties(ROOT::ASImageGui PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf2d/asimage/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Gui;ROOT::ASImage"
)

# Create imported target ROOT::FITSIO
add_library(ROOT::FITSIO SHARED IMPORTED)

set_target_properties(ROOT::FITSIO PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf2d/fitsio/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Gpad;ROOT::Graf;ROOT::Hist;ROOT::Matrix"
)

# Create imported target ROOT::Graf3d
add_library(ROOT::Graf3d SHARED IMPORTED)

set_target_properties(ROOT::Graf3d PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf3d/g3d/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Gpad;ROOT::Graf;ROOT::Hist;ROOT::MathCore"
)

# Create imported target ROOT::X3d
add_library(ROOT::X3d SHARED IMPORTED)

set_target_properties(ROOT::X3d PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf3d/x3d/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Graf3d;ROOT::Gui"
)

# Create imported target ROOT::RCsg
add_library(ROOT::RCsg SHARED IMPORTED)

set_target_properties(ROOT::RCsg PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf3d/csg/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::MathCore"
)

# Create imported target ROOT::Eve
add_library(ROOT::Eve SHARED IMPORTED)

set_target_properties(ROOT::Eve PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf3d/eve/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::EG;ROOT::Ged;ROOT::Geom;ROOT::RGL;ROOT::Physics"
)

# Create imported target ROOT::RGL
add_library(ROOT::RGL SHARED IMPORTED)

set_target_properties(ROOT::RGL PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf3d/gl/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Hist;ROOT::Gui;ROOT::Ged;ROOT::RCsg"
)

# Create imported target ROOT::Gviz3d
add_library(ROOT::Gviz3d SHARED IMPORTED)

set_target_properties(ROOT::Gviz3d PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/graf3d/gviz3d/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Gui;ROOT::Ged;ROOT::Geom;ROOT::RGL"
)

# Create imported target ROOT::Gui
add_library(ROOT::Gui SHARED IMPORTED)

set_target_properties(ROOT::Gui PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/gui/gui/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::Gpad;ROOT::Graf;ROOT::MathCore"
)

# Create imported target ROOT::Ged
add_library(ROOT::Ged SHARED IMPORTED)

set_target_properties(ROOT::Ged PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/gui/ged/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Hist;ROOT::Gpad;ROOT::Graf;ROOT::Gui;ROOT::Tree;ROOT::TreePlayer"
)

# Create imported target ROOT::FitPanel
add_library(ROOT::FitPanel SHARED IMPORTED)

set_target_properties(ROOT::FitPanel PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/gui/fitpanel/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Gpad;ROOT::Graf;ROOT::Gui;ROOT::Hist;ROOT::MathCore;ROOT::Tree;ROOT::TreePlayer"
)

# Create imported target ROOT::GuiBld
add_library(ROOT::GuiBld SHARED IMPORTED)

set_target_properties(ROOT::GuiBld PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/gui/guibuilder/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Gui;ROOT::Graf;ROOT::MathCore"
)

# Create imported target ROOT::GuiHtml
add_library(ROOT::GuiHtml SHARED IMPORTED)

set_target_properties(ROOT::GuiHtml PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/gui/guihtml/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Gui;ROOT::Graf;ROOT::Net"
)

# Create imported target ROOT::Recorder
add_library(ROOT::Recorder SHARED IMPORTED)

set_target_properties(ROOT::Recorder PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/gui/recorder/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::RIO;ROOT::Tree;ROOT::Gui;ROOT::Thread"
)

# Create imported target ROOT::SessionViewer
add_library(ROOT::SessionViewer SHARED IMPORTED)

set_target_properties(ROOT::SessionViewer PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/gui/sessionviewer/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Proof;ROOT::Gui;ROOT::Hist;ROOT::Gpad;ROOT::Graf;ROOT::Tree;ROOT::MathCore"
)

# Create imported target ROOT::Proof
add_library(ROOT::Proof SHARED IMPORTED)

set_target_properties(ROOT::Proof PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/proof/proof/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::MathCore;ROOT::Net;ROOT::RIO;ROOT::Thread;ROOT::Tree"
)

# Create imported target ROOT::ProofPlayer
add_library(ROOT::ProofPlayer SHARED IMPORTED)

set_target_properties(ROOT::ProofPlayer PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/proof/proofplayer/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Hist;ROOT::Net;ROOT::MathCore;ROOT::Proof;ROOT::RIO;ROOT::Thread;ROOT::Tree;ROOT::TreePlayer"
)

# Create imported target ROOT::ProofDraw
add_library(ROOT::ProofDraw SHARED IMPORTED)

set_target_properties(ROOT::ProofDraw PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/proof/proofplayer/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::ProofPlayer;ROOT::TreePlayer"
)

# Create imported target ROOT::ProofBench
add_library(ROOT::ProofBench SHARED IMPORTED)

set_target_properties(ROOT::ProofBench PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/proof/proofbench/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::Gpad;ROOT::Hist;ROOT::ProofPlayer"
)

# Create imported target ROOT::Html
add_library(ROOT::Html SHARED IMPORTED)

set_target_properties(ROOT::Html PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/html/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Graf;ROOT::Thread"
)

# Create imported target ROOT::EG
add_library(ROOT::EG SHARED IMPORTED)

set_target_properties(ROOT::EG PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/montecarlo/eg/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Gpad;ROOT::Graf;ROOT::Graf3d;ROOT::MathCore;ROOT::Physics"
)

# Create imported target ROOT::Geom
add_library(ROOT::Geom SHARED IMPORTED)

set_target_properties(ROOT::Geom PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/geom/geom/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Thread;ROOT::RIO;ROOT::MathCore;ROOT::Hist"
)

# Create imported target ROOT::GeomBuilder
add_library(ROOT::GeomBuilder SHARED IMPORTED)

set_target_properties(ROOT::GeomBuilder PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/geom/geombuilder/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Geom;ROOT::Graf3d;ROOT::Gpad;ROOT::Graf;ROOT::Gui;ROOT::Ged"
)

# Create imported target ROOT::GeomPainter
add_library(ROOT::GeomPainter SHARED IMPORTED)

set_target_properties(ROOT::GeomPainter PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/geom/geompainter/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Geom;ROOT::Gpad;ROOT::Graf3d;ROOT::Hist;ROOT::RIO;ROOT::Tree"
)

# Create imported target ROOT::Gdml
add_library(ROOT::Gdml SHARED IMPORTED)

set_target_properties(ROOT::Gdml PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/geom/gdml/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Geom;ROOT::XMLIO;ROOT::Hist;ROOT::RIO"
)

# Create imported target ROOT::root
add_executable(ROOT::root IMPORTED)

# Create imported target ROOT::rootn.exe
add_executable(ROOT::rootn.exe IMPORTED)

# Create imported target ROOT::roots.exe
add_executable(ROOT::roots.exe IMPORTED)

# Create imported target ROOT::xpdtest
add_executable(ROOT::xpdtest IMPORTED)

# Create imported target ROOT::root.exe
add_executable(ROOT::root.exe IMPORTED)

# Create imported target ROOT::proofserv.exe
add_executable(ROOT::proofserv.exe IMPORTED)

# Create imported target ROOT::hadd
add_executable(ROOT::hadd IMPORTED)

# Create imported target ROOT::rootnb.exe
add_executable(ROOT::rootnb.exe IMPORTED)

# Create imported target ROOT::rootcling
add_executable(ROOT::rootcling IMPORTED)

# Create imported target ROOT::cppyy_backend3_7
add_library(ROOT::cppyy_backend3_7 SHARED IMPORTED)

set_target_properties(ROOT::cppyy_backend3_7 PROPERTIES
  INTERFACE_LINK_LIBRARIES "ROOT::Core;dl"
)

# Create imported target ROOT::cppyy_backend2_7
add_library(ROOT::cppyy_backend2_7 SHARED IMPORTED)

set_target_properties(ROOT::cppyy_backend2_7 PROPERTIES
  INTERFACE_LINK_LIBRARIES "ROOT::Core;dl"
)

# Create imported target ROOT::cppyy3_7
add_library(ROOT::cppyy3_7 SHARED IMPORTED)

set_target_properties(ROOT::cppyy3_7 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/python3.7m;/home/nicobigio01/colab_root/root_src/bindings/pyroot/cppyy/CPyCppyy/inc;/home/nicobigio01/colab_root/root_src/bindings/pyroot/cppyy/CPyCppyy/src"
  INTERFACE_LINK_LIBRARIES "-Wl,--unresolved-symbols=ignore-all;ROOT::cppyy_backend3_7"
)

# Create imported target ROOT::cppyy2_7
add_library(ROOT::cppyy2_7 SHARED IMPORTED)

set_target_properties(ROOT::cppyy2_7 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/python2.7;/home/nicobigio01/colab_root/root_src/bindings/pyroot/cppyy/CPyCppyy/inc;/home/nicobigio01/colab_root/root_src/bindings/pyroot/cppyy/CPyCppyy/src"
  INTERFACE_LINK_LIBRARIES "-Wl,--unresolved-symbols=ignore-all;ROOT::cppyy_backend2_7"
)

# Create imported target ROOT::ROOTTPython
add_library(ROOT::ROOTTPython SHARED IMPORTED)

set_target_properties(ROOT::ROOTTPython PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/bindings/tpython/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::RMySQL
add_library(ROOT::RMySQL SHARED IMPORTED)

set_target_properties(ROOT::RMySQL PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/sql/mysql/inc;/usr/include/mysql"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::Net;ROOT::RIO;-L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -ldl -lz -lssl -lcrypto -lresolv -lm -lrt"
)

# Create imported target ROOT::TMVA
add_library(ROOT::TMVA SHARED IMPORTED)

set_target_properties(ROOT::TMVA PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/tmva/tmva/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::TreePlayer;ROOT::Tree;ROOT::Hist;ROOT::Matrix;ROOT::Minuit;ROOT::MLP;ROOT::MathCore;ROOT::Core;ROOT::RIO;ROOT::XMLIO;ROOT::ROOTDataFrame;ROOT::ROOTVecOps;ROOT::Imt"
)

# Create imported target ROOT::TMVAGui
add_library(ROOT::TMVAGui SHARED IMPORTED)

set_target_properties(ROOT::TMVAGui PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/tmva/tmvagui/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::RIO;ROOT::Hist;ROOT::Tree;ROOT::TreeViewer;ROOT::MLP;ROOT::Minuit;ROOT::XMLIO;ROOT::TMVA;ROOT::Gui;ROOT::HistPainter;ROOT::Core"
)

# Create imported target ROOT::ROOTTMVASofie
add_library(ROOT::ROOTTMVASofie SHARED IMPORTED)

set_target_properties(ROOT::ROOTTMVASofie PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/tmva/sofie/inc;/home/nicobigio01/colab_root/root_build/tmva/sofie"
  INTERFACE_LINK_LIBRARIES "ROOT::TMVA"
)

# Create imported target ROOT::RooBatchCompute
add_library(ROOT::RooBatchCompute SHARED IMPORTED)

set_target_properties(ROOT::RooBatchCompute PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/roofit/batchcompute/inc;/home/nicobigio01/colab_root/root_build/ginclude"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::MathCore;ROOT::Imt"
)

# Create imported target ROOT::RooBatchCompute_GENERIC
add_library(ROOT::RooBatchCompute_GENERIC SHARED IMPORTED)

set_target_properties(ROOT::RooBatchCompute_GENERIC PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/roofit/batchcompute/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::RooBatchCompute"
)

# Create imported target ROOT::RooBatchCompute_SSE4.1
add_library(ROOT::RooBatchCompute_SSE4.1 SHARED IMPORTED)

set_target_properties(ROOT::RooBatchCompute_SSE4.1 PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/roofit/batchcompute/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::RooBatchCompute"
)

# Create imported target ROOT::RooBatchCompute_AVX
add_library(ROOT::RooBatchCompute_AVX SHARED IMPORTED)

set_target_properties(ROOT::RooBatchCompute_AVX PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/roofit/batchcompute/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::RooBatchCompute"
)

# Create imported target ROOT::RooBatchCompute_AVX2
add_library(ROOT::RooBatchCompute_AVX2 SHARED IMPORTED)

set_target_properties(ROOT::RooBatchCompute_AVX2 PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/roofit/batchcompute/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::RooBatchCompute"
)

# Create imported target ROOT::RooBatchCompute_AVX512
add_library(ROOT::RooBatchCompute_AVX512 SHARED IMPORTED)

set_target_properties(ROOT::RooBatchCompute_AVX512 PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/roofit/batchcompute/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::RooBatchCompute"
)

# Create imported target ROOT::RooFitCommon
add_library(ROOT::RooFitCommon SHARED IMPORTED)

set_target_properties(ROOT::RooFitCommon PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_LINK_LIBRARIES "ROOT::Core"
)

# Create imported target ROOT::RooFitCore
add_library(ROOT::RooFitCore SHARED IMPORTED)

set_target_properties(ROOT::RooFitCore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_COMPILE_OPTIONS "-fno-math-errno"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/roofit/roofitcore/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::Hist;ROOT::Graf;ROOT::Matrix;ROOT::Tree;ROOT::Minuit;ROOT::Minuit2;ROOT::RIO;ROOT::MathCore;ROOT::Foam;ROOT::Smatrix"
)

# Create imported target ROOT::RooFit
add_library(ROOT::RooFit SHARED IMPORTED)

set_target_properties(ROOT::RooFit PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_COMPILE_OPTIONS "-fno-math-errno"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/roofit/roofit/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::RooFitCore;ROOT::Tree;ROOT::RIO;ROOT::Matrix;ROOT::MathCore"
)

# Create imported target ROOT::RooFitMore
add_library(ROOT::RooFitMore SHARED IMPORTED)

set_target_properties(ROOT::RooFitMore PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_COMPILE_OPTIONS "-fno-math-errno"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/roofit/roofitmore/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::MathMore;ROOT::Core;ROOT::RooFitCore;ROOT::RooFit;ROOT::Hist;ROOT::Matrix;ROOT::Tree;ROOT::Minuit;ROOT::RIO;ROOT::MathCore;ROOT::Foam"
)

# Create imported target ROOT::RooStats
add_library(ROOT::RooStats SHARED IMPORTED)

set_target_properties(ROOT::RooStats PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/roofit/roostats/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;ROOT::RooFit;ROOT::RooFitCore;ROOT::Tree;ROOT::RIO;ROOT::Hist;ROOT::Matrix;ROOT::MathCore;ROOT::Minuit;ROOT::Foam;ROOT::Graf;ROOT::Gpad"
)

# Create imported target ROOT::HistFactory
add_library(ROOT::HistFactory SHARED IMPORTED)

set_target_properties(ROOT::HistFactory PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_COMPILE_OPTIONS "-fno-math-errno"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/roofit/histfactory/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::RooFit;ROOT::RooFitCore;ROOT::Tree;ROOT::RIO;ROOT::Hist;ROOT::Matrix;ROOT::MathCore;ROOT::Graf;ROOT::Gpad;ROOT::RooStats;ROOT::XMLParser"
)

# Create imported target ROOT::hist2workspace
add_executable(ROOT::hist2workspace IMPORTED)

# Create imported target ROOT::RooFitRDataFrameHelpers
add_library(ROOT::RooFitRDataFrameHelpers SHARED IMPORTED)

set_target_properties(ROOT::RooFitRDataFrameHelpers PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/roofit/RDataFrameHelpers/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::ROOTDataFrame;ROOT::RooFitCore"
)

# Create imported target ROOT::RooFitHS3
add_library(ROOT::RooFitHS3 SHARED IMPORTED)

set_target_properties(ROOT::RooFitHS3 PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/home/nicobigio01/colab_root/root_src/roofit/hs3/inc"
  INTERFACE_LINK_LIBRARIES "ROOT::RooFit;ROOT::RooFitCore;ROOT::RooStats;ROOT::HistFactory"
)

# Import target "ROOT::vectorDict" for configuration "Release"
set_property(TARGET ROOT::vectorDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::vectorDict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libvectorDict.so"
  IMPORTED_SONAME_RELEASE "libvectorDict.so"
  )

# Import target "ROOT::listDict" for configuration "Release"
set_property(TARGET ROOT::listDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::listDict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/liblistDict.so"
  IMPORTED_SONAME_RELEASE "liblistDict.so"
  )

# Import target "ROOT::forward_listDict" for configuration "Release"
set_property(TARGET ROOT::forward_listDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::forward_listDict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libforward_listDict.so"
  IMPORTED_SONAME_RELEASE "libforward_listDict.so"
  )

# Import target "ROOT::dequeDict" for configuration "Release"
set_property(TARGET ROOT::dequeDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::dequeDict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libdequeDict.so"
  IMPORTED_SONAME_RELEASE "libdequeDict.so"
  )

# Import target "ROOT::mapDict" for configuration "Release"
set_property(TARGET ROOT::mapDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::mapDict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libmapDict.so"
  IMPORTED_SONAME_RELEASE "libmapDict.so"
  )

# Import target "ROOT::map2Dict" for configuration "Release"
set_property(TARGET ROOT::map2Dict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::map2Dict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libmap2Dict.so"
  IMPORTED_SONAME_RELEASE "libmap2Dict.so"
  )

# Import target "ROOT::unordered_mapDict" for configuration "Release"
set_property(TARGET ROOT::unordered_mapDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::unordered_mapDict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libunordered_mapDict.so"
  IMPORTED_SONAME_RELEASE "libunordered_mapDict.so"
  )

# Import target "ROOT::multimapDict" for configuration "Release"
set_property(TARGET ROOT::multimapDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::multimapDict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libmultimapDict.so"
  IMPORTED_SONAME_RELEASE "libmultimapDict.so"
  )

# Import target "ROOT::multimap2Dict" for configuration "Release"
set_property(TARGET ROOT::multimap2Dict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::multimap2Dict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libmultimap2Dict.so"
  IMPORTED_SONAME_RELEASE "libmultimap2Dict.so"
  )

# Import target "ROOT::unordered_multimapDict" for configuration "Release"
set_property(TARGET ROOT::unordered_multimapDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::unordered_multimapDict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libunordered_multimapDict.so"
  IMPORTED_SONAME_RELEASE "libunordered_multimapDict.so"
  )

# Import target "ROOT::setDict" for configuration "Release"
set_property(TARGET ROOT::setDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::setDict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libsetDict.so"
  IMPORTED_SONAME_RELEASE "libsetDict.so"
  )

# Import target "ROOT::unordered_setDict" for configuration "Release"
set_property(TARGET ROOT::unordered_setDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::unordered_setDict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libunordered_setDict.so"
  IMPORTED_SONAME_RELEASE "libunordered_setDict.so"
  )

# Import target "ROOT::multisetDict" for configuration "Release"
set_property(TARGET ROOT::multisetDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::multisetDict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libmultisetDict.so"
  IMPORTED_SONAME_RELEASE "libmultisetDict.so"
  )

# Import target "ROOT::unordered_multisetDict" for configuration "Release"
set_property(TARGET ROOT::unordered_multisetDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::unordered_multisetDict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libunordered_multisetDict.so"
  IMPORTED_SONAME_RELEASE "libunordered_multisetDict.so"
  )

# Import target "ROOT::complexDict" for configuration "Release"
set_property(TARGET ROOT::complexDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::complexDict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libcomplexDict.so"
  IMPORTED_SONAME_RELEASE "libcomplexDict.so"
  )

# Import target "ROOT::valarrayDict" for configuration "Release"
set_property(TARGET ROOT::valarrayDict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::valarrayDict PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libvalarrayDict.so"
  IMPORTED_SONAME_RELEASE "libvalarrayDict.so"
  )

# Import target "ROOT::Cling" for configuration "Release"
set_property(TARGET ROOT::Cling APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Cling PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libCling.so"
  IMPORTED_SONAME_RELEASE "libCling.so"
  )

# Import target "ROOT::MultiProc" for configuration "Release"
set_property(TARGET ROOT::MultiProc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::MultiProc PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libMultiProc.so"
  IMPORTED_SONAME_RELEASE "libMultiProc.so"
  )

# Import target "ROOT::Rint" for configuration "Release"
set_property(TARGET ROOT::Rint APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Rint PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRint.so"
  IMPORTED_SONAME_RELEASE "libRint.so"
  )

# Import target "ROOT::Thread" for configuration "Release"
set_property(TARGET ROOT::Thread APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Thread PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libThread.so"
  IMPORTED_SONAME_RELEASE "libThread.so"
  )

# Import target "ROOT::Imt" for configuration "Release"
set_property(TARGET ROOT::Imt APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Imt PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ROOT::Thread"
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libImt.so"
  IMPORTED_SONAME_RELEASE "libImt.so"
  )

# Import target "ROOT::New" for configuration "Release"
set_property(TARGET ROOT::New APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::New PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libNew.so"
  IMPORTED_SONAME_RELEASE "libNew.so"
  )

# Import target "ROOT::rootcling_stage1" for configuration "Release"
set_property(TARGET ROOT::rootcling_stage1 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::rootcling_stage1 PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/core/rootcling_stage1/src/rootcling_stage1"
  )

# Import target "ROOT::Core" for configuration "Release"
set_property(TARGET ROOT::Core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Core PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libCore.so"
  IMPORTED_SONAME_RELEASE "libCore.so"
  )

# Import target "ROOT::rmkdepend" for configuration "Release"
set_property(TARGET ROOT::rmkdepend APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::rmkdepend PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/bin/rmkdepend"
  )

# Import target "ROOT::MathCore" for configuration "Release"
set_property(TARGET ROOT::MathCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::MathCore PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libMathCore.so"
  IMPORTED_SONAME_RELEASE "libMathCore.so"
  )

# Import target "ROOT::MathMore" for configuration "Release"
set_property(TARGET ROOT::MathMore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::MathMore PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libMathMore.so"
  IMPORTED_SONAME_RELEASE "libMathMore.so"
  )

# Import target "ROOT::Matrix" for configuration "Release"
set_property(TARGET ROOT::Matrix APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Matrix PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libMatrix.so"
  IMPORTED_SONAME_RELEASE "libMatrix.so"
  )

# Import target "ROOT::Minuit" for configuration "Release"
set_property(TARGET ROOT::Minuit APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Minuit PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libMinuit.so"
  IMPORTED_SONAME_RELEASE "libMinuit.so"
  )

# Import target "ROOT::Minuit2" for configuration "Release"
set_property(TARGET ROOT::Minuit2 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Minuit2 PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libMinuit2.so"
  IMPORTED_SONAME_RELEASE "libMinuit2.so"
  )

# Import target "ROOT::Fumili" for configuration "Release"
set_property(TARGET ROOT::Fumili APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Fumili PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libFumili.so"
  IMPORTED_SONAME_RELEASE "libFumili.so"
  )

# Import target "ROOT::Physics" for configuration "Release"
set_property(TARGET ROOT::Physics APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Physics PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libPhysics.so"
  IMPORTED_SONAME_RELEASE "libPhysics.so"
  )

# Import target "ROOT::MLP" for configuration "Release"
set_property(TARGET ROOT::MLP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::MLP PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libMLP.so"
  IMPORTED_SONAME_RELEASE "libMLP.so"
  )

# Import target "ROOT::Quadp" for configuration "Release"
set_property(TARGET ROOT::Quadp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Quadp PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libQuadp.so"
  IMPORTED_SONAME_RELEASE "libQuadp.so"
  )

# Import target "ROOT::Foam" for configuration "Release"
set_property(TARGET ROOT::Foam APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Foam PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libFoam.so"
  IMPORTED_SONAME_RELEASE "libFoam.so"
  )

# Import target "ROOT::Smatrix" for configuration "Release"
set_property(TARGET ROOT::Smatrix APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Smatrix PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libSmatrix.so"
  IMPORTED_SONAME_RELEASE "libSmatrix.so"
  )

# Import target "ROOT::SPlot" for configuration "Release"
set_property(TARGET ROOT::SPlot APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::SPlot PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libSPlot.so"
  IMPORTED_SONAME_RELEASE "libSPlot.so"
  )

# Import target "ROOT::GenVector" for configuration "Release"
set_property(TARGET ROOT::GenVector APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::GenVector PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGenVector.so"
  IMPORTED_SONAME_RELEASE "libGenVector.so"
  )

# Import target "ROOT::Genetic" for configuration "Release"
set_property(TARGET ROOT::Genetic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Genetic PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGenetic.so"
  IMPORTED_SONAME_RELEASE "libGenetic.so"
  )

# Import target "ROOT::FFTW" for configuration "Release"
set_property(TARGET ROOT::FFTW APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::FFTW PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libFFTW.so"
  IMPORTED_SONAME_RELEASE "libFFTW.so"
  )

# Import target "ROOT::ROOTVecOps" for configuration "Release"
set_property(TARGET ROOT::ROOTVecOps APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::ROOTVecOps PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libROOTVecOps.so"
  IMPORTED_SONAME_RELEASE "libROOTVecOps.so"
  )

# Import target "ROOT::Hist" for configuration "Release"
set_property(TARGET ROOT::Hist APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Hist PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libHist.so"
  IMPORTED_SONAME_RELEASE "libHist.so"
  )

# Import target "ROOT::HistPainter" for configuration "Release"
set_property(TARGET ROOT::HistPainter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::HistPainter PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libHistPainter.so"
  IMPORTED_SONAME_RELEASE "libHistPainter.so"
  )

# Import target "ROOT::Spectrum" for configuration "Release"
set_property(TARGET ROOT::Spectrum APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Spectrum PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libSpectrum.so"
  IMPORTED_SONAME_RELEASE "libSpectrum.so"
  )

# Import target "ROOT::SpectrumPainter" for configuration "Release"
set_property(TARGET ROOT::SpectrumPainter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::SpectrumPainter PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libSpectrumPainter.so"
  IMPORTED_SONAME_RELEASE "libSpectrumPainter.so"
  )

# Import target "ROOT::Unfold" for configuration "Release"
set_property(TARGET ROOT::Unfold APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Unfold PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libUnfold.so"
  IMPORTED_SONAME_RELEASE "libUnfold.so"
  )

# Import target "ROOT::Tree" for configuration "Release"
set_property(TARGET ROOT::Tree APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Tree PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libTree.so"
  IMPORTED_SONAME_RELEASE "libTree.so"
  )

# Import target "ROOT::TreePlayer" for configuration "Release"
set_property(TARGET ROOT::TreePlayer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::TreePlayer PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libTreePlayer.so"
  IMPORTED_SONAME_RELEASE "libTreePlayer.so"
  )

# Import target "ROOT::TreeViewer" for configuration "Release"
set_property(TARGET ROOT::TreeViewer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::TreeViewer PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libTreeViewer.so"
  IMPORTED_SONAME_RELEASE "libTreeViewer.so"
  )

# Import target "ROOT::ROOTDataFrame" for configuration "Release"
set_property(TARGET ROOT::ROOTDataFrame APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::ROOTDataFrame PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libROOTDataFrame.so"
  IMPORTED_SONAME_RELEASE "libROOTDataFrame.so"
  )

# Import target "ROOT::RIO" for configuration "Release"
set_property(TARGET ROOT::RIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RIO PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRIO.so"
  IMPORTED_SONAME_RELEASE "libRIO.so"
  )

# Import target "ROOT::SQLIO" for configuration "Release"
set_property(TARGET ROOT::SQLIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::SQLIO PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libSQLIO.so"
  IMPORTED_SONAME_RELEASE "libSQLIO.so"
  )

# Import target "ROOT::XMLIO" for configuration "Release"
set_property(TARGET ROOT::XMLIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::XMLIO PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libXMLIO.so"
  IMPORTED_SONAME_RELEASE "libXMLIO.so"
  )

# Import target "ROOT::XMLParser" for configuration "Release"
set_property(TARGET ROOT::XMLParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::XMLParser PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libXMLParser.so"
  IMPORTED_SONAME_RELEASE "libXMLParser.so"
  )

# Import target "ROOT::Net" for configuration "Release"
set_property(TARGET ROOT::Net APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Net PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libNet.so"
  IMPORTED_SONAME_RELEASE "libNet.so"
  )

# Import target "ROOT::RootAuth" for configuration "Release"
set_property(TARGET ROOT::RootAuth APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RootAuth PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRootAuth.so"
  IMPORTED_SONAME_RELEASE "libRootAuth.so"
  )

# Import target "ROOT::SrvAuth" for configuration "Release"
set_property(TARGET ROOT::SrvAuth APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::SrvAuth PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libSrvAuth.so"
  IMPORTED_SONAME_RELEASE "libSrvAuth.so"
  )

# Import target "ROOT::NetxNG" for configuration "Release"
set_property(TARGET ROOT::NetxNG APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::NetxNG PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libNetxNG.so"
  IMPORTED_SONAME_RELEASE "libNetxNG.so"
  )

# Import target "ROOT::RHTTP" for configuration "Release"
set_property(TARGET ROOT::RHTTP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RHTTP PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRHTTP.so"
  IMPORTED_SONAME_RELEASE "libRHTTP.so"
  )

# Import target "ROOT::RHTTPSniff" for configuration "Release"
set_property(TARGET ROOT::RHTTPSniff APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RHTTPSniff PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRHTTPSniff.so"
  IMPORTED_SONAME_RELEASE "libRHTTPSniff.so"
  )

# Import target "ROOT::Gpad" for configuration "Release"
set_property(TARGET ROOT::Gpad APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Gpad PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGpad.so"
  IMPORTED_SONAME_RELEASE "libGpad.so"
  )

# Import target "ROOT::Graf" for configuration "Release"
set_property(TARGET ROOT::Graf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Graf PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGraf.so"
  IMPORTED_SONAME_RELEASE "libGraf.so"
  )

# Import target "ROOT::Postscript" for configuration "Release"
set_property(TARGET ROOT::Postscript APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Postscript PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libPostscript.so"
  IMPORTED_SONAME_RELEASE "libPostscript.so"
  )

# Import target "ROOT::mathtext" for configuration "Release"
set_property(TARGET ROOT::mathtext APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::mathtext PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libmathtext.a"
  )

# Import target "ROOT::GX11" for configuration "Release"
set_property(TARGET ROOT::GX11 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::GX11 PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGX11.so"
  IMPORTED_SONAME_RELEASE "libGX11.so"
  )

# Import target "ROOT::GX11TTF" for configuration "Release"
set_property(TARGET ROOT::GX11TTF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::GX11TTF PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGX11TTF.so"
  IMPORTED_SONAME_RELEASE "libGX11TTF.so"
  )

# Import target "ROOT::ASImage" for configuration "Release"
set_property(TARGET ROOT::ASImage APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::ASImage PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libASImage.so"
  IMPORTED_SONAME_RELEASE "libASImage.so"
  )

# Import target "ROOT::ASImageGui" for configuration "Release"
set_property(TARGET ROOT::ASImageGui APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::ASImageGui PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libASImageGui.so"
  IMPORTED_SONAME_RELEASE "libASImageGui.so"
  )

# Import target "ROOT::FITSIO" for configuration "Release"
set_property(TARGET ROOT::FITSIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::FITSIO PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libFITSIO.so"
  IMPORTED_SONAME_RELEASE "libFITSIO.so"
  )

# Import target "ROOT::Graf3d" for configuration "Release"
set_property(TARGET ROOT::Graf3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Graf3d PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGraf3d.so"
  IMPORTED_SONAME_RELEASE "libGraf3d.so"
  )

# Import target "ROOT::X3d" for configuration "Release"
set_property(TARGET ROOT::X3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::X3d PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libX3d.so"
  IMPORTED_SONAME_RELEASE "libX3d.so"
  )

# Import target "ROOT::RCsg" for configuration "Release"
set_property(TARGET ROOT::RCsg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RCsg PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRCsg.so"
  IMPORTED_SONAME_RELEASE "libRCsg.so"
  )

# Import target "ROOT::Eve" for configuration "Release"
set_property(TARGET ROOT::Eve APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Eve PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libEve.so"
  IMPORTED_SONAME_RELEASE "libEve.so"
  )

# Import target "ROOT::RGL" for configuration "Release"
set_property(TARGET ROOT::RGL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RGL PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRGL.so"
  IMPORTED_SONAME_RELEASE "libRGL.so"
  )

# Import target "ROOT::Gviz3d" for configuration "Release"
set_property(TARGET ROOT::Gviz3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Gviz3d PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGviz3d.so"
  IMPORTED_SONAME_RELEASE "libGviz3d.so"
  )

# Import target "ROOT::Gui" for configuration "Release"
set_property(TARGET ROOT::Gui APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Gui PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGui.so"
  IMPORTED_SONAME_RELEASE "libGui.so"
  )

# Import target "ROOT::Ged" for configuration "Release"
set_property(TARGET ROOT::Ged APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Ged PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGed.so"
  IMPORTED_SONAME_RELEASE "libGed.so"
  )

# Import target "ROOT::FitPanel" for configuration "Release"
set_property(TARGET ROOT::FitPanel APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::FitPanel PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libFitPanel.so"
  IMPORTED_SONAME_RELEASE "libFitPanel.so"
  )

# Import target "ROOT::GuiBld" for configuration "Release"
set_property(TARGET ROOT::GuiBld APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::GuiBld PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGuiBld.so"
  IMPORTED_SONAME_RELEASE "libGuiBld.so"
  )

# Import target "ROOT::GuiHtml" for configuration "Release"
set_property(TARGET ROOT::GuiHtml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::GuiHtml PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGuiHtml.so"
  IMPORTED_SONAME_RELEASE "libGuiHtml.so"
  )

# Import target "ROOT::Recorder" for configuration "Release"
set_property(TARGET ROOT::Recorder APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Recorder PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRecorder.so"
  IMPORTED_SONAME_RELEASE "libRecorder.so"
  )

# Import target "ROOT::SessionViewer" for configuration "Release"
set_property(TARGET ROOT::SessionViewer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::SessionViewer PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libSessionViewer.so"
  IMPORTED_SONAME_RELEASE "libSessionViewer.so"
  )

# Import target "ROOT::Proof" for configuration "Release"
set_property(TARGET ROOT::Proof APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Proof PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libProof.so"
  IMPORTED_SONAME_RELEASE "libProof.so"
  )

# Import target "ROOT::ProofPlayer" for configuration "Release"
set_property(TARGET ROOT::ProofPlayer APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::ProofPlayer PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libProofPlayer.so"
  IMPORTED_SONAME_RELEASE "libProofPlayer.so"
  )

# Import target "ROOT::ProofDraw" for configuration "Release"
set_property(TARGET ROOT::ProofDraw APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::ProofDraw PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libProofDraw.so"
  IMPORTED_SONAME_RELEASE "libProofDraw.so"
  )

# Import target "ROOT::ProofBench" for configuration "Release"
set_property(TARGET ROOT::ProofBench APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::ProofBench PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libProofBench.so"
  IMPORTED_SONAME_RELEASE "libProofBench.so"
  )

# Import target "ROOT::Html" for configuration "Release"
set_property(TARGET ROOT::Html APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Html PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libHtml.so"
  IMPORTED_SONAME_RELEASE "libHtml.so"
  )

# Import target "ROOT::EG" for configuration "Release"
set_property(TARGET ROOT::EG APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::EG PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libEG.so"
  IMPORTED_SONAME_RELEASE "libEG.so"
  )

# Import target "ROOT::Geom" for configuration "Release"
set_property(TARGET ROOT::Geom APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Geom PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGeom.so"
  IMPORTED_SONAME_RELEASE "libGeom.so"
  )

# Import target "ROOT::GeomBuilder" for configuration "Release"
set_property(TARGET ROOT::GeomBuilder APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::GeomBuilder PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGeomBuilder.so"
  IMPORTED_SONAME_RELEASE "libGeomBuilder.so"
  )

# Import target "ROOT::GeomPainter" for configuration "Release"
set_property(TARGET ROOT::GeomPainter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::GeomPainter PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGeomPainter.so"
  IMPORTED_SONAME_RELEASE "libGeomPainter.so"
  )

# Import target "ROOT::Gdml" for configuration "Release"
set_property(TARGET ROOT::Gdml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::Gdml PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libGdml.so"
  IMPORTED_SONAME_RELEASE "libGdml.so"
  )

# Import target "ROOT::root" for configuration "Release"
set_property(TARGET ROOT::root APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::root PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/bin/root"
  )

# Import target "ROOT::rootn.exe" for configuration "Release"
set_property(TARGET ROOT::rootn.exe APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::rootn.exe PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/bin/rootn.exe"
  )

# Import target "ROOT::roots.exe" for configuration "Release"
set_property(TARGET ROOT::roots.exe APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::roots.exe PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/bin/roots.exe"
  )

# Import target "ROOT::xpdtest" for configuration "Release"
set_property(TARGET ROOT::xpdtest APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::xpdtest PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/bin/xpdtest"
  )

# Import target "ROOT::root.exe" for configuration "Release"
set_property(TARGET ROOT::root.exe APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::root.exe PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/bin/root.exe"
  )

# Import target "ROOT::proofserv.exe" for configuration "Release"
set_property(TARGET ROOT::proofserv.exe APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::proofserv.exe PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/bin/proofserv.exe"
  )

# Import target "ROOT::hadd" for configuration "Release"
set_property(TARGET ROOT::hadd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::hadd PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/bin/hadd"
  )

# Import target "ROOT::rootnb.exe" for configuration "Release"
set_property(TARGET ROOT::rootnb.exe APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::rootnb.exe PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/bin/rootnb.exe"
  )

# Import target "ROOT::rootcling" for configuration "Release"
set_property(TARGET ROOT::rootcling APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::rootcling PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/bin/rootcling"
  )

# Import target "ROOT::cppyy_backend3_7" for configuration "Release"
set_property(TARGET ROOT::cppyy_backend3_7 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::cppyy_backend3_7 PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libcppyy_backend3_7.so"
  IMPORTED_SONAME_RELEASE "libcppyy_backend3_7.so"
  )

# Import target "ROOT::cppyy_backend2_7" for configuration "Release"
set_property(TARGET ROOT::cppyy_backend2_7 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::cppyy_backend2_7 PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libcppyy_backend2_7.so"
  IMPORTED_SONAME_RELEASE "libcppyy_backend2_7.so"
  )

# Import target "ROOT::cppyy3_7" for configuration "Release"
set_property(TARGET ROOT::cppyy3_7 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::cppyy3_7 PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libcppyy3_7.so"
  IMPORTED_SONAME_RELEASE "libcppyy3_7.so"
  )

# Import target "ROOT::cppyy2_7" for configuration "Release"
set_property(TARGET ROOT::cppyy2_7 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::cppyy2_7 PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libcppyy2_7.so"
  IMPORTED_SONAME_RELEASE "libcppyy2_7.so"
  )

# Import target "ROOT::ROOTTPython" for configuration "Release"
set_property(TARGET ROOT::ROOTTPython APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::ROOTTPython PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ROOT::cppyy3_7"
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libROOTTPython.so"
  IMPORTED_SONAME_RELEASE "libROOTTPython.so"
  )

# Import target "ROOT::RMySQL" for configuration "Release"
set_property(TARGET ROOT::RMySQL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RMySQL PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRMySQL.so"
  IMPORTED_SONAME_RELEASE "libRMySQL.so"
  )

# Import target "ROOT::TMVA" for configuration "Release"
set_property(TARGET ROOT::TMVA APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::TMVA PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libTMVA.so"
  IMPORTED_SONAME_RELEASE "libTMVA.so"
  )

# Import target "ROOT::TMVAGui" for configuration "Release"
set_property(TARGET ROOT::TMVAGui APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::TMVAGui PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libTMVAGui.so"
  IMPORTED_SONAME_RELEASE "libTMVAGui.so"
  )

# Import target "ROOT::ROOTTMVASofie" for configuration "Release"
set_property(TARGET ROOT::ROOTTMVASofie APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::ROOTTMVASofie PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libROOTTMVASofie.so"
  IMPORTED_SONAME_RELEASE "libROOTTMVASofie.so"
  )

# Import target "ROOT::RooBatchCompute" for configuration "Release"
set_property(TARGET ROOT::RooBatchCompute APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RooBatchCompute PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRooBatchCompute.so"
  IMPORTED_SONAME_RELEASE "libRooBatchCompute.so"
  )

# Import target "ROOT::RooBatchCompute_GENERIC" for configuration "Release"
set_property(TARGET ROOT::RooBatchCompute_GENERIC APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RooBatchCompute_GENERIC PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRooBatchCompute_GENERIC.so"
  IMPORTED_SONAME_RELEASE "libRooBatchCompute_GENERIC.so"
  )

# Import target "ROOT::RooBatchCompute_SSE4.1" for configuration "Release"
set_property(TARGET ROOT::RooBatchCompute_SSE4.1 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RooBatchCompute_SSE4.1 PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRooBatchCompute_SSE4.1.so"
  IMPORTED_SONAME_RELEASE "libRooBatchCompute_SSE4.1.so"
  )

# Import target "ROOT::RooBatchCompute_AVX" for configuration "Release"
set_property(TARGET ROOT::RooBatchCompute_AVX APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RooBatchCompute_AVX PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRooBatchCompute_AVX.so"
  IMPORTED_SONAME_RELEASE "libRooBatchCompute_AVX.so"
  )

# Import target "ROOT::RooBatchCompute_AVX2" for configuration "Release"
set_property(TARGET ROOT::RooBatchCompute_AVX2 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RooBatchCompute_AVX2 PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRooBatchCompute_AVX2.so"
  IMPORTED_SONAME_RELEASE "libRooBatchCompute_AVX2.so"
  )

# Import target "ROOT::RooBatchCompute_AVX512" for configuration "Release"
set_property(TARGET ROOT::RooBatchCompute_AVX512 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RooBatchCompute_AVX512 PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRooBatchCompute_AVX512.so"
  IMPORTED_SONAME_RELEASE "libRooBatchCompute_AVX512.so"
  )

# Import target "ROOT::RooFitCommon" for configuration "Release"
set_property(TARGET ROOT::RooFitCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RooFitCommon PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRooFitCommon.so"
  IMPORTED_SONAME_RELEASE "libRooFitCommon.so"
  )

# Import target "ROOT::RooFitCore" for configuration "Release"
set_property(TARGET ROOT::RooFitCore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RooFitCore PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ROOT::RooBatchCompute;ROOT::RooFitCommon"
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRooFitCore.so"
  IMPORTED_SONAME_RELEASE "libRooFitCore.so"
  )

# Import target "ROOT::RooFit" for configuration "Release"
set_property(TARGET ROOT::RooFit APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RooFit PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ROOT::RooBatchCompute"
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRooFit.so"
  IMPORTED_SONAME_RELEASE "libRooFit.so"
  )

# Import target "ROOT::RooFitMore" for configuration "Release"
set_property(TARGET ROOT::RooFitMore APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RooFitMore PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ROOT::RooBatchCompute"
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRooFitMore.so"
  IMPORTED_SONAME_RELEASE "libRooFitMore.so"
  )

# Import target "ROOT::RooStats" for configuration "Release"
set_property(TARGET ROOT::RooStats APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RooStats PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRooStats.so"
  IMPORTED_SONAME_RELEASE "libRooStats.so"
  )

# Import target "ROOT::HistFactory" for configuration "Release"
set_property(TARGET ROOT::HistFactory APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::HistFactory PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ROOT::RooBatchCompute"
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libHistFactory.so"
  IMPORTED_SONAME_RELEASE "libHistFactory.so"
  )

# Import target "ROOT::hist2workspace" for configuration "Release"
set_property(TARGET ROOT::hist2workspace APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::hist2workspace PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/bin/hist2workspace"
  )

# Import target "ROOT::RooFitRDataFrameHelpers" for configuration "Release"
set_property(TARGET ROOT::RooFitRDataFrameHelpers APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RooFitRDataFrameHelpers PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRooFitRDataFrameHelpers.so"
  IMPORTED_SONAME_RELEASE "libRooFitRDataFrameHelpers.so"
  )

# Import target "ROOT::RooFitHS3" for configuration "Release"
set_property(TARGET ROOT::RooFitHS3 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ROOT::RooFitHS3 PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nicobigio01/colab_root/root_build/lib/libRooFitHS3.so"
  IMPORTED_SONAME_RELEASE "libRooFitHS3.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
