
cmake_minimum_required(VERSION 3.15)

set(command "/usr/bin/cmake;-G;Unix Makefiles;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_C_COMPILER=/usr/bin/cc;-DCMAKE_C_FLAGS= -Wno-implicit-fallthrough -pipe -Wall -W -pthread -fPIC;-DCMAKE_CXX_COMPILER=/usr/bin/c++;-DCMAKE_CXX_FLAGS= -std=c++14 -Wno-implicit-fallthrough -Wno-noexcept-type -pipe  -Wshadow -Wall -W -Woverloaded-virtual -fsigned-char -pthread -fno-semantic-interposition   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-strict-aliasing -Wwrite-strings -Wno-shadow -Wno-unused-parameter -Wno-deprecated-declarations -fPIC -fno-rtti;-DCMAKE_INSTALL_PREFIX=/home/nicobigio01/colab_root/root_build/etc/cling//plugins;-DLLVM_DIR=/home/nicobigio01/colab_root/root_build/interpreter/llvm/src;-DCLANG_INCLUDE_DIRS=/home/nicobigio01/colab_root/root_src/interpreter/llvm/src/tools/clang/include;/home/nicobigio01/colab_root/root_build/interpreter/llvm/src/tools/clang/include;-DCMAKE_CXX_STANDARD=14;-DClang_DIR=/home/nicobigio01/colab_root/root_build/interpreter/llvm/src/tools/clang/;-DClang_CONFIG_EXTRA_PATH_HINTS=;-DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=ON;-DCLAD_BUILD_STATIC_ONLY=ON;-GUnix Makefiles;/home/nicobigio01/colab_root/root_build/interpreter/cling/tools/plugins/clad/clad-prefix/src/clad")
set(log_merged "")
set(log_output_on_failure "ON")
set(stdout_log "/home/nicobigio01/colab_root/root_build/interpreter/cling/tools/plugins/clad/clad-prefix/src/clad-stamp/clad-configure-out.log")
set(stderr_log "/home/nicobigio01/colab_root/root_build/interpreter/cling/tools/plugins/clad/clad-prefix/src/clad-stamp/clad-configure-err.log")
execute_process(
  COMMAND ${command}
  RESULT_VARIABLE result
  OUTPUT_FILE "${stdout_log}"
  ERROR_FILE "${stderr_log}"
  )
macro(read_up_to_max_size log_file output_var)
  file(SIZE ${log_file} determined_size)
  set(max_size 10240)
  if (determined_size GREATER max_size)
    math(EXPR seek_position "${determined_size} - ${max_size}")
    file(READ ${log_file} ${output_var} OFFSET ${seek_position})
    set(${output_var} "...skipping to end...\n${${output_var}}")
  else()
    file(READ ${log_file} ${output_var})
  endif()
endmacro()
if(result)
  set(msg "Command failed: ${result}\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  if (${log_merged})
    set(msg "${msg}\nSee also\n  ${stderr_log}")
  else()
    set(msg "${msg}\nSee also\n  /home/nicobigio01/colab_root/root_build/interpreter/cling/tools/plugins/clad/clad-prefix/src/clad-stamp/clad-configure-*.log")
  endif()
  if (${log_output_on_failure})
    message(SEND_ERROR "${msg}")
    if (${log_merged})
      read_up_to_max_size("${stderr_log}" error_log_contents)
      message(STATUS "Log output is:\n${error_log_contents}")
    else()
      read_up_to_max_size("${stdout_log}" out_log_contents)
      read_up_to_max_size("${stderr_log}" err_log_contents)
      message(STATUS "stdout output is:\n${out_log_contents}")
      message(STATUS "stderr output is:\n${err_log_contents}")
    endif()
    message(FATAL_ERROR "Stopping after outputting logs.")
  else()
    message(FATAL_ERROR "${msg}")
  endif()
else()
  set(msg "clad configure command succeeded.  See also /home/nicobigio01/colab_root/root_build/interpreter/cling/tools/plugins/clad/clad-prefix/src/clad-stamp/clad-configure-*.log")
  message(STATUS "${msg}")
endif()
