# -*- mode: makefile -*-
#
# Makefile compiler definitions included by the top Makefile.
# Used to override the compilers specified in the architecture
# specific Makefiles.

CC    = gcc-7
CXX   = g++-7
F77   = CMAKE_Fortran_COMPILER-NOTFOUND
LD    = g++-7
GCCTOOLCHAIN = 
