// STL headers
#if __has_include("cstdlib")
#include <cstdlib>
#endif
#if __has_include("csignal")
#include <csignal>
#endif
#if __has_include("csetjmp")
#include <csetjmp>
#endif
#if __has_include("cstdarg")
#include <cstdarg>
#endif
#if __has_include("typeinfo")
#include <typeinfo>
#endif
#if __has_include("typeindex")
#include <typeindex>
#endif
#if __has_include("type_traits")
#include <type_traits>
#endif
#if __has_include("bitset")
#include <bitset>
#endif
#if __has_include("functional")
#include <functional>
#endif
#if __has_include("utility")
#include <utility>
#endif
#if __has_include("ctime")
#include <ctime>
#endif
#if __has_include("chrono")
#include <chrono>
#endif
#if __has_include("cstddef")
#include <cstddef>
#endif
#if __has_include("initializer_list")
#include <initializer_list>
#endif
#if __has_include("tuple")
#include <tuple>
#endif
#if __has_include("new")
#include <new>
#endif
#if __has_include("memory")
#include <memory>
#endif
#if __has_include("scoped_allocator")
#include <scoped_allocator>
#endif
#if __has_include("climits")
#include <climits>
#endif
#if __has_include("cfloat")
#include <cfloat>
#endif
#if __has_include("cstdint")
#include <cstdint>
#endif
#if __has_include("cinttypes")
#include <cinttypes>
#endif
#if __has_include("limits")
#include <limits>
#endif
#if __has_include("exception")
#include <exception>
#endif
#if __has_include("stdexcept")
#include <stdexcept>
#endif
#if __has_include("cassert")
#include <cassert>
#endif
#if __has_include("system_error")
#include <system_error>
#endif
#if __has_include("cerrno")
#include <cerrno>
#endif
#if __has_include("cctype")
#include <cctype>
#endif
#if __has_include("cwctype")
#include <cwctype>
#endif
#if __has_include("cstring")
#include <cstring>
#endif
#if __has_include("cwchar")
#include <cwchar>
#endif
#if __has_include("cuchar")
#include <cuchar>
#endif
#if __has_include("string")
#include <string>
#endif
#if __has_include("array")
#include <array>
#endif
#if __has_include("vector")
#include <vector>
#endif
#if __has_include("deque")
#include <deque>
#endif
#if __has_include("list")
#include <list>
#endif
#if __has_include("forward_list")
#include <forward_list>
#endif
#if __has_include("set")
#include <set>
#endif
#if __has_include("map")
#include <map>
#endif
#if __has_include("unordered_set")
#include <unordered_set>
#endif
#if __has_include("unordered_map")
#include <unordered_map>
#endif
#if __has_include("stack")
#include <stack>
#endif
#if __has_include("queue")
#include <queue>
#endif
#if __has_include("algorithm")
#include <algorithm>
#endif
#if __has_include("iterator")
#include <iterator>
#endif
#if __has_include("cmath")
#include <cmath>
#endif
#if __has_include("complex")
#include <complex>
#endif
#if __has_include("random")
#include <random>
#endif
#if __has_include("numeric")
#include <numeric>
#endif
#if __has_include("ratio")
#include <ratio>
#endif
#if __has_include("cfenv")
#include <cfenv>
#endif
#if __has_include("iosfwd")
#include <iosfwd>
#endif
#if __has_include("ios")
#include <ios>
#endif
#if __has_include("istream")
#include <istream>
#endif
#if __has_include("ostream")
#include <ostream>
#endif
#if __has_include("iostream")
#include <iostream>
#endif
#if __has_include("fstream")
#include <fstream>
#endif
#if __has_include("sstream")
#include <sstream>
#endif
#if __has_include("iomanip")
#include <iomanip>
#endif
#if __has_include("streambuf")
#include <streambuf>
#endif
#if __has_include("cstdio")
#include <cstdio>
#endif
#if __has_include("locale")
#include <locale>
#endif
#if __has_include("clocale")
#include <clocale>
#endif
#if __has_include("codecvt")
#include <codecvt>
#endif
#if __has_include("atomic")
#include <atomic>
#endif
#if __has_include("thread")
#include <thread>
#endif
#if __has_include("mutex")
#include <mutex>
#endif
#if __has_include("future")
#include <future>
#endif
#if __has_include("condition_variable")
#include <condition_variable>
#endif
#if __has_include("ciso646")
#include <ciso646>
#endif
#if __has_include("ccomplex")
#include <ccomplex>
#endif
#if __has_include("ctgmath")
#include <ctgmath>
#endif
#if __has_include("regex")
#include <regex>
#endif
#if __has_include("cstdbool")
#include <cstdbool>
#endif
// treat regex separately
#if __has_include("regex") && !defined __APPLE__
#include <regex>
#endif
// STL Deprecated headers
#define _BACKWARD_BACKWARD_WARNING_H
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated"
#if __has_include("strstream")
#include <strstream>
#endif
#pragma clang diagnostic pop
#undef _BACKWARD_BACKWARD_WARNING_H
#include "etc/cling/Interpreter/DynamicExprInfo.h"
#include "etc/cling/Interpreter/DynamicLookupRuntimeUniverse.h"
#include "etc/cling/Interpreter/DynamicLookupLifetimeHandler.h"
#include "etc/cling/Interpreter/Exception.h"
#include "etc/cling/Interpreter/RuntimePrintValue.h"
#include "etc/cling/Interpreter/RuntimeUniverse.h"
#include "etc/cling/Interpreter/RuntimeOptions.h"
#include "etc/cling/Interpreter/Value.h"
#include "etc/cling/Interpreter/Visibility.h"
// ./graf2d/graf/G__Graf.cxx
#include "TArc.h"
#include "TArrow.h"
#include "TAttImage.h"
#include "TBox.h"
#include "TCandle.h"
#include "TCrown.h"
#include "TCurlyArc.h"
#include "TCurlyLine.h"
#include "TCutG.h"
#include "TDiamond.h"
#include "TEllipse.h"
#include "TFrame.h"
#include "TGaxis.h"
#include "TGraphPolar.h"
#include "TGraphPolargram.h"
#include "TGraphQQ.h"
#include "TImage.h"
#include "TImagePlugin.h"
#include "TLatex.h"
#include "TLegend.h"
#include "TLegendEntry.h"
#include "TLine.h"
#include "TLink.h"
#include "TMarker.h"
#include "TMathText.h"
#include "TPave.h"
#include "TPaveLabel.h"
#include "TPaveStats.h"
#include "TPaveText.h"
#include "TPavesText.h"
#include "TPie.h"
#include "TPieSlice.h"
#include "TPoints.h"
#include "TPolyLine.h"
#include "TTF.h"
#include "TText.h"
#include "TWbox.h"
// ./graf2d/gpad/G__Gpad.cxx
#include "TAttCanvas.h"
#include "TButton.h"
#include "TCanvas.h"
#include "TClassTree.h"
#include "TColorWheel.h"
#include "TControlBarButton.h"
#include "TControlBar.h"
#include "TCreatePrimitives.h"
#include "TDialogCanvas.h"
#include "TGroupButton.h"
#include "TInspectCanvas.h"
#include "TPad.h"
#include "TPadPainter.h"
#include "TPaveClass.h"
#include "TRatioPlot.h"
#include "TSliderBox.h"
#include "TSlider.h"
#include "TViewer3DPad.h"
#include "TView.h"
// ./graf2d/postscript/G__Postscript.cxx
#include "TImageDump.h"
#include "TPDF.h"
#include "TPostScript.h"
#include "TSVG.h"
#include "TTeXDump.h"
// ./tree/tree/G__Tree.cxx
#include "TBasket.h"
#include "TBasketSQL.h"
#include "TBranchBrowsable.h"
#include "TBranchCacheInfo.h"
#include "TBranchClones.h"
#include "TBranchElement.h"
#include "TBranch.h"
#include "TBranchObject.h"
#include "TBranchRef.h"
#include "TBranchSTL.h"
#include "TBufferSQL.h"
#include "TChainElement.h"
#include "TChain.h"
#include "TCut.h"
#include "TEntryListArray.h"
#include "TEntryListBlock.h"
#include "TEntryListFromFile.h"
#include "TEntryList.h"
#include "TEventList.h"
#include "TFriendElement.h"
#include "TIndArray.h"
#include "TLeafB.h"
#include "TLeafC.h"
#include "TLeafD.h"
#include "TLeafD32.h"
#include "TLeafElement.h"
#include "TLeafF.h"
#include "TLeafF16.h"
#include "TLeaf.h"
#include "TLeafI.h"
#include "TLeafL.h"
#include "TLeafG.h"
#include "TLeafObject.h"
#include "TLeafO.h"
#include "TLeafS.h"
#include "TNtupleD.h"
#include "TNtuple.h"
#include "TQueryResult.h"
#include "TreeUtils.h"
#include "TSelector.h"
#include "TSelectorList.h"
#include "TSelectorScalar.h"
#include "TTreeCache.h"
#include "TTreeCacheUnzip.h"
#include "TTreeCloner.h"
#include "TTree.h"
#include "TTreeResult.h"
#include "TTreeRow.h"
#include "TTreeSQL.h"
#include "TVirtualIndex.h"
#include "TVirtualTreePlayer.h"
#include "ROOT/InternalTreeUtils.hxx"
#include "ROOT/TIOFeatures.hxx"
// ./tree/treeplayer/G__TreePlayer.cxx
#include "ROOT/TTreeReaderFast.hxx"
#include "ROOT/TTreeReaderValueFast.hxx"
#include "TBranchProxyClassDescriptor.h"
#include "TBranchProxyDescriptor.h"
#include "TBranchProxyDirector.h"
#include "TBranchProxy.h"
#include "TChainIndex.h"
#include "TFileDrawMap.h"
#include "TFormLeafInfo.h"
#include "TFormLeafInfoReference.h"
#include "TFriendProxyDescriptor.h"
#include "TFriendProxy.h"
#include "TRefArrayProxy.h"
#include "TRefProxy.h"
#include "TSelectorDraw.h"
#include "TSelectorEntries.h"
#include "TSimpleAnalysis.h"
#include "TTreeDrawArgsParser.h"
#include "TTreeFormula.h"
#include "TTreeFormulaManager.h"
#include "TTreeGeneratorBase.h"
#include "TTreeIndex.h"
#include "TTreePerfStats.h"
#include "TTreePlayer.h"
#include "TTreeProxyGenerator.h"
#include "TTreeReaderArray.h"
#include "TTreeReaderGenerator.h"
#include "TTreeReader.h"
#include "TTreeReaderUtils.h"
#include "TTreeReaderValue.h"
#include "TTreeTableInterface.h"
#include "TMPWorkerTree.h"
#include "ROOT/TTreeProcessorMP.hxx"
// ./tree/treeviewer/G__TreeViewer.cxx
#include "HelpTextTV.h"
#include "TGTreeTable.h"
#include "TParallelCoordEditor.h"
#include "TParallelCoord.h"
#include "TParallelCoordRange.h"
#include "TParallelCoordVar.h"
#include "TSpiderEditor.h"
#include "TSpider.h"
#include "TTreeViewer.h"
#include "TTVLVContainer.h"
#include "TTVSession.h"
// ./graf3d/g3d/G__Graf3d.cxx
#include "TAxis3D.h"
#include "TBRIK.h"
#include "TCONE.h"
#include "TCONS.h"
#include "TCTUB.h"
#include "TELTU.h"
#include "TGeometry.h"
#include "TGTRA.h"
#include "THelix.h"
#include "THYPE.h"
#include "TMarker3DBox.h"
#include "TMaterial.h"
#include "TMixture.h"
#include "TNodeDiv.h"
#include "TNode.h"
#include "TPARA.h"
#include "TPCON.h"
#include "TPGON.h"
#include "TPoints3DABC.h"
#include "TPointSet3D.h"
#include "TPolyLine3D.h"
#include "TPolyMarker3D.h"
#include "TRotMatrix.h"
#include "TShape.h"
#include "TSPHE.h"
#include "TTRAP.h"
#include "TTRD1.h"
#include "TTRD2.h"
#include "TTUBE.h"
#include "TTUBS.h"
#include "TView3D.h"
#include "TXTRU.h"
#include "X3DBuffer.h"
// ./io/io/G__RIO.cxx
#include "ROOT/RRawFile.hxx"
#include "ROOT/RRawFileUnix.hxx"
#include "ROOT/TBufferMerger.hxx"
#include "TArchiveFile.h"
#include "TBufferFile.h"
#include "TBufferText.h"
#include "TBufferIO.h"
#include "TBufferJSON.h"
#include "TCollectionProxyFactory.h"
#include "TContainerConverters.h"
#include "TEmulatedMapProxy.h"
#include "TEmulatedCollectionProxy.h"
#include "TDirectoryFile.h"
#include "TFileCacheRead.h"
#include "TFileMerger.h"
#include "TFree.h"
#include "TFileCacheWrite.h"
#include "TFilePrefetch.h"
#include "TFile.h"
#include "TFPBlock.h"
#include "TGenCollectionStreamer.h"
#include "TGenCollectionProxy.h"
#include "TKey.h"
#include "TKeyMapFile.h"
#include "TLockFile.h"
#include "TMemFile.h"
#include "TMapFile.h"
#include "TMakeProject.h"
#include "TStreamerInfoActions.h"
#include "TVirtualCollectionIterators.h"
#include "TStreamerInfo.h"
#include "TZIPFile.h"
// ./hist/histpainter/G__HistPainter.cxx
#include "Hoption.h"
#include "Hparam.h"
#include "TGraph2DPainter.h"
#include "TGraphPainter.h"
#include "THistPainter.h"
#include "TPaletteAxis.h"
// ./hist/hist/G__Hist.cxx
#include "Foption.h"
#include "HFitInterface.h"
#include "TAxis.h"
#include "TAxisModLab.h"
#include "TBackCompFitter.h"
#include "TBinomialEfficiencyFitter.h"
#include "TConfidenceLevel.h"
#include "TEfficiency.h"
#include "TF12.h"
#include "TF1AbsComposition.h"
#include "TF1Convolution.h"
#include "TF1.h"
#include "TF1NormSum.h"
#include "TF2.h"
#include "TF3.h"
#include "TFitResult.h"
#include "TFitResultPtr.h"
#include "TFormula.h"
#include "TFractionFitter.h"
#include "THistRange.h"
#include "TGraph2DErrors.h"
#include "TGraph2D.h"
#include "TGraphAsymmErrors.h"
#include "TGraphMultiErrors.h"
#include "TGraphBentErrors.h"
#include "TGraphDelaunay2D.h"
#include "TGraphDelaunay.h"
#include "TGraphErrors.h"
#include "TGraph.h"
#include "TGraphSmooth.h"
#include "TGraphTime.h"
#include "TH1C.h"
#include "TH1D.h"
#include "TH1F.h"
#include "TH1.h"
#include "TH1I.h"
#include "TH1K.h"
#include "TH1S.h"
#include "TH2C.h"
#include "TH2D.h"
#include "TH2F.h"
#include "TH2.h"
#include "TH2I.h"
#include "TH2Poly.h"
#include "TH2S.h"
#include "TH3C.h"
#include "TH3D.h"
#include "TH3F.h"
#include "TH3.h"
#include "TH3I.h"
#include "TH3S.h"
#include "THLimitsFinder.h"
#include "THnBase.h"
#include "THnChain.h"
#include "THn.h"
#include "THnSparse.h"
#include "THnSparse_Internal.h"
#include "THStack.h"
#include "TKDE.h"
#include "TLimitDataSource.h"
#include "TLimit.h"
#include "TMultiDimFit.h"
#include "TMultiGraph.h"
#include "TNDArray.h"
#include "TPolyMarker.h"
#include "TPrincipal.h"
#include "TProfile2D.h"
#include "TProfile2Poly.h"
#include "TProfile3D.h"
#include "TProfile.h"
#include "TSpline.h"
#include "TSVDUnfold.h"
#include "TVirtualFitter.h"
#include "TVirtualGraphPainter.h"
#include "TVirtualHistPainter.h"
#include "TVirtualPaveStats.h"
#include "Math/WrappedMultiTF1.h"
#include "Math/WrappedTF1.h"
#include "v5/TF1Data.h"
#include "v5/TFormula.h"
#include "v5/TFormulaPrimitive.h"
// ./net/net/G__Net.cxx
#include "NetErrors.h"
#include "RRemoteProtocol.h"
#include "TApplicationRemote.h"
#include "TApplicationServer.h"
#include "TFileStager.h"
#include "TFTP.h"
#include "TGrid.h"
#include "TGridCollection.h"
#include "TGridJDL.h"
#include "TGridJob.h"
#include "TGridJobStatus.h"
#include "TGridJobStatusList.h"
#include "TGridResult.h"
#include "TMessage.h"
#include "TMonitor.h"
#include "TNetFile.h"
#include "TNetFileStager.h"
#include "TParallelMergingFile.h"
#include "TPServerSocket.h"
#include "TPSocket.h"
#include "TSecContext.h"
#include "TServerSocket.h"
#include "TSocket.h"
#include "TSQLColumnInfo.h"
#include "TSQLMonitoring.h"
#include "TSQLResult.h"
#include "TSQLRow.h"
#include "TSQLServer.h"
#include "TSQLStatement.h"
#include "TSQLTableInfo.h"
#include "TUDPSocket.h"
#include "TWebFile.h"
// ./gui/fitpanel/G__FitPanel.cxx
#include "TAdvancedGraphicsDialog.h"
#include "TFitEditor.h"
#include "TFitParametersDialog.h"
#include "TTreeInput.h"
// ./gui/gui/G__Gui.cxx
#include "HelpText.h"
#include "TG3DLine.h"
#include "TGApplication.h"
#include "TGButton.h"
#include "TGButtonGroup.h"
#include "TGCanvas.h"
#include "TGClient.h"
#include "TGColorDialog.h"
#include "TGColorSelect.h"
#include "TGComboBox.h"
#include "TGCommandPlugin.h"
#include "TGDNDManager.h"
#include "TGDimension.h"
#include "TGDockableFrame.h"
#include "TGDoubleSlider.h"
#include "TGEventHandler.h"
#include "TGFSComboBox.h"
#include "TGFSContainer.h"
#include "TGFileBrowser.h"
#include "TGFileDialog.h"
#include "TGFont.h"
#include "TGFontDialog.h"
#include "TGFrame.h"
#include "TGGC.h"
#include "TGIcon.h"
#include "TGIdleHandler.h"
#include "TGImageMap.h"
#include "TGInputDialog.h"
#include "TGLabel.h"
#include "TGLayout.h"
#include "TGListBox.h"
#include "TGListTree.h"
#include "TGListView.h"
#include "TGMdi.h"
#include "TGMdiDecorFrame.h"
#include "TGMdiFrame.h"
#include "TGMdiMainFrame.h"
#include "TGMdiMenu.h"
#include "TGMenu.h"
#include "TGMimeTypes.h"
#include "TGMsgBox.h"
#include "TGNumberEntry.h"
#include "TGObject.h"
#include "TGPack.h"
#include "TGPasswdDialog.h"
#include "TGPicture.h"
#include "TGProgressBar.h"
#include "TGRedirectOutputGuard.h"
#include "TGResourcePool.h"
#include "TGScrollBar.h"
#include "TGShapedFrame.h"
#include "TGShutter.h"
#include "TGSimpleTable.h"
#include "TGSimpleTableInterface.h"
#include "TGSlider.h"
#include "TGSpeedo.h"
#include "TGSplitFrame.h"
#include "TGSplitter.h"
#include "TGStatusBar.h"
#include "TGString.h"
#include "TGTab.h"
#include "TGTable.h"
#include "TGTableCell.h"
#include "TGTableContainer.h"
#include "TGTableHeader.h"
#include "TGTableLayout.h"
#include "TGText.h"
#include "TGTextBuffer.h"
#include "TGTextEdit.h"
#include "TGTextEditDialogs.h"
#include "TGTextEditor.h"
#include "TGTextEntry.h"
#include "TGTextView.h"
#include "TGTextViewStream.h"
#include "TGToolBar.h"
#include "TGToolTip.h"
#include "TGTripleSlider.h"
#include "TGView.h"
#include "TGWidget.h"
#include "TGWindow.h"
#include "TGXYLayout.h"
#include "TGuiBuilder.h"
#include "TRootApplication.h"
#include "TRootBrowser.h"
#include "TRootBrowserLite.h"
#include "TRootCanvas.h"
#include "TRootContextMenu.h"
#include "TRootControlBar.h"
#include "TRootDialog.h"
#include "TRootEmbeddedCanvas.h"
#include "TRootGuiFactory.h"
#include "TRootHelpDialog.h"
#include "TVirtualDragManager.h"
#include "WidgetMessageTypes.h"
// ./core/imt/G__Imt.cxx
#include "ROOT/TExecutor.hxx"
// ./core/multiproc/G__MultiProc.cxx
#include "MPCode.h"
#include "MPSendRecv.h"
#include "PoolUtils.h"
#include "TMPClient.h"
#include "TMPWorker.h"
#include "TMPWorkerExecutor.h"
#include "TProcPool.h"
#include "ROOT/TProcessExecutor.hxx"
// ./core/rint/G__Rint.cxx
#include "TRint.h"
#include "TTabCom.h"
// ./core/thread/G__Thread.cxx
#include "TPosixCondition.h"
#include "TPosixMutex.h"
#include "TPosixThread.h"
#include "TPosixThreadFactory.h"
#include "PosixThreadInc.h"
#include "TAtomicCount.h"
#include "TCondition.h"
#include "TConditionImp.h"
#include "ThreadLocalStorage.h"
#include "TMutex.h"
#include "TMutexImp.h"
#include "TRWLock.h"
#include "TSemaphore.h"
#include "TThreadFactory.h"
#include "TThread.h"
#include "TThreadImp.h"
#include "TThreadPool.h"
#include "ROOT/RConcurrentHashColl.hxx"
#include "ROOT/TRWSpinLock.hxx"
#include "ROOT/TSpinMutex.hxx"
#include "ROOT/TThreadedObject.hxx"
// ./core/clingutils/G__dequeDict.cxx
#include "deque"
// ./core/clingutils/G__vectorDict.cxx
#include "vector"
// ./core/clingutils/G__map2Dict.cxx
#include "map"
// ./core/clingutils/G__unordered_mapDict.cxx
#include "unordered_map"
// ./core/clingutils/G__setDict.cxx
#include "set"
// ./core/clingutils/G__complexDict.cxx
#include "root_std_complex.h"
// ./core/clingutils/G__mapDict.cxx
#include "map"
// ./core/clingutils/G__multimap2Dict.cxx
#include "map"
// ./core/clingutils/G__valarrayDict.cxx
#include "valarray"
// ./core/clingutils/G__unordered_multimapDict.cxx
#include "unordered_map"
// ./core/clingutils/G__unordered_setDict.cxx
#include "unordered_set"
// ./core/clingutils/G__forward_listDict.cxx
#include "forward_list"
// ./core/clingutils/G__multimapDict.cxx
#include "map"
// ./core/clingutils/G__unordered_multisetDict.cxx
#include "unordered_set"
// ./core/clingutils/G__listDict.cxx
#include "list"
// ./core/clingutils/G__multisetDict.cxx
#include "set"
// ./math/matrix/G__Matrix.cxx
#include "TDecompBK.h"
#include "TDecompBase.h"
#include "TDecompChol.h"
#include "TDecompLU.h"
#include "TDecompQRH.h"
#include "TDecompSVD.h"
#include "TDecompSparse.h"
#include "TMatrix.h"
#include "TMatrixD.h"
#include "TMatrixDBase.h"
#include "TMatrixDBasefwd.h"
#include "TMatrixDEigen.h"
#include "TMatrixDLazy.h"
#include "TMatrixDSparse.h"
#include "TMatrixDSparsefwd.h"
#include "TMatrixDSym.h"
#include "TMatrixDSymEigen.h"
#include "TMatrixDSymfwd.h"
#include "TMatrixDUtils.h"
#include "TMatrixDUtilsfwd.h"
#include "TMatrixDfwd.h"
#include "TMatrixF.h"
#include "TMatrixFBase.h"
#include "TMatrixFBasefwd.h"
#include "TMatrixFLazy.h"
#include "TMatrixFSparse.h"
#include "TMatrixFSparsefwd.h"
#include "TMatrixFSym.h"
#include "TMatrixFSymfwd.h"
#include "TMatrixFUtils.h"
#include "TMatrixFUtilsfwd.h"
#include "TMatrixFfwd.h"
#include "TMatrixT.h"
#include "TMatrixTBase.h"
#include "TMatrixTCramerInv.h"
#include "TMatrixTLazy.h"
#include "TMatrixTSparse.h"
#include "TMatrixTSym.h"
#include "TMatrixTSymCramerInv.h"
#include "TMatrixTUtils.h"
#include "TVector.h"
#include "TVectorD.h"
#include "TVectorDfwd.h"
#include "TVectorF.h"
#include "TVectorFfwd.h"
#include "TVectorT.h"
#include "TVectorfwd.h"
// ./math/mathcore/G__MathCore.cxx
#include "Fit/BasicFCN.h"
#include "Fit/BinData.h"
#include "Fit/Chi2FCN.h"
#include "Fit/DataOptions.h"
#include "Fit/DataRange.h"
#include "Fit/FcnAdapter.h"
#include "Fit/FitConfig.h"
#include "Fit/FitData.h"
#include "Fit/FitExecutionPolicy.h"
#include "Fit/FitResult.h"
#include "Fit/FitUtil.h"
#include "Fit/Fitter.h"
#include "Fit/LogLikelihoodFCN.h"
#include "Fit/ParameterSettings.h"
#include "Fit/PoissonLikelihoodFCN.h"
#include "Fit/SparseData.h"
#include "Fit/UnBinData.h"
#include "Math/AdaptiveIntegratorMultiDim.h"
#include "Math/AllIntegrationTypes.h"
#include "Math/BasicMinimizer.h"
#include "Math/BrentMethods.h"
#include "Math/BrentMinimizer1D.h"
#include "Math/BrentRootFinder.h"
#include "Math/ChebyshevPol.h"
#include "Math/Delaunay2D.h"
#include "Math/DistFuncMathCore.h"
#include "Math/DistSampler.h"
#include "Math/DistSamplerOptions.h"
#include "Math/Error.h"
#include "Math/Factory.h"
#include "Math/FitMethodFunction.h"
#include "Math/Functor.h"
#include "Math/GaussIntegrator.h"
#include "Math/GaussLegendreIntegrator.h"
#include "Math/GenAlgoOptions.h"
#include "Math/GoFTest.h"
#include "Math/IFunction.h"
#include "Math/IFunctionfwd.h"
#include "Math/IMinimizer1D.h"
#include "Math/IOptions.h"
#include "Math/IParamFunction.h"
#include "Math/IParamFunctionfwd.h"
#include "Math/IRootFinderMethod.h"
#include "Math/Integrator.h"
#include "Math/IntegratorMultiDim.h"
#include "Math/IntegratorOptions.h"
#include "Math/KDTree.h"
#include "Math/LCGEngine.h"
#include "Math/Math.h"
#include "Math/MersenneTwisterEngine.h"
#include "Math/MinimTransformFunction.h"
#include "Math/MinimTransformVariable.h"
#include "Math/Minimizer.h"
#include "Math/MinimizerOptions.h"
#include "Math/MinimizerVariableTransformation.h"
#include "Math/MixMaxEngine.h"
#include "Math/MultiDimParamFunctionAdapter.h"
#include "Math/OneDimFunctionAdapter.h"
#include "Math/ParamFunctor.h"
#include "Math/PdfFuncMathCore.h"
#include "Math/ProbFuncMathCore.h"
#include "Math/QuantFuncMathCore.h"
#include "Math/Random.h"
#include "Math/RandomFunctions.h"
#include "Math/RanluxppEngine.h"
#include "Math/RichardsonDerivator.h"
#include "Math/RootFinder.h"
#include "Math/SpecFuncMathCore.h"
#include "Math/StdEngine.h"
#include "Math/TDataPoint.h"
#include "Math/TDataPointN.h"
#include "Math/TRandomEngine.h"
#include "Math/Types.h"
#include "Math/Util.h"
#include "Math/VirtualIntegrator.h"
#include "Math/WrappedFunction.h"
#include "Math/WrappedParamFunction.h"
#include "TComplex.h"
#include "TKDTree.h"
#include "TKDTreeBinning.h"
#include "TMath.h"
#include "TRandom.h"
#include "TRandom1.h"
#include "TRandom2.h"
#include "TRandom3.h"
#include "TRandomGen.h"
#include "TStatistic.h"
#include "VectorizedTMath.h"
// ./math/smatrix/G__Smatrix.cxx
#include "Math/BinaryOperators.h"
#include "Math/BinaryOpPolicy.h"
#include "Math/CholeskyDecomp.h"
#include "Math/Dfact.h"
#include "Math/Dfactir.h"
#include "Math/Dfinv.h"
#include "Math/Dinv.h"
#include "Math/Dsfact.h"
#include "Math/Dsinv.h"
#include "Math/Expression.h"
#include "Math/Functions.h"
#include "Math/HelperOps.h"
#include "Math/MatrixFunctions.h"
#include "Math/MatrixRepresentationsStatic.h"
#include "Math/MConfig.h"
#include "Math/SMatrixDfwd.h"
#include "Math/SMatrixFfwd.h"
#include "Math/SMatrix.h"
#include "Math/StaticCheck.h"
#include "Math/SVector.h"
#include "Math/UnaryOperators.h"
// ./math/smatrix/G__Smatrix32.cxx
#include "Math/SMatrix.h"
#include "Math/SMatrixDfwd.h"
#include "Math/SMatrixFfwd.h"
#include "Math/SVector.h"
// ./math/genvector/G__GenVector.cxx
#include "Math/AxisAngle.h"
#include "Math/Boost.h"
#include "Math/BoostX.h"
#include "Math/BoostY.h"
#include "Math/BoostZ.h"
#include "Math/Cartesian2D.h"
#include "Math/Cartesian3D.h"
#include "Math/Cylindrical3D.h"
#include "Math/CylindricalEta3D.h"
#include "Math/DisplacementVector2D.h"
#include "Math/DisplacementVector3D.h"
#include "Math/EulerAngles.h"
#include "Math/GenVector/3DConversions.h"
#include "Math/GenVector/3DDistances.h"
#include "Math/GenVector/AxisAnglefwd.h"
#include "Math/GenVector/AxisAngle.h"
#include "Math/GenVector/BitReproducible.h"
#include "Math/GenVector/Boostfwd.h"
#include "Math/GenVector/Boost.h"
#include "Math/GenVector/BoostXfwd.h"
#include "Math/GenVector/BoostX.h"
#include "Math/GenVector/BoostYfwd.h"
#include "Math/GenVector/BoostY.h"
#include "Math/GenVector/BoostZfwd.h"
#include "Math/GenVector/BoostZ.h"
#include "Math/GenVector/Cartesian2Dfwd.h"
#include "Math/GenVector/Cartesian2D.h"
#include "Math/GenVector/Cartesian3Dfwd.h"
#include "Math/GenVector/Cartesian3D.h"
#include "Math/GenVector/CoordinateSystemTags.h"
#include "Math/GenVector/Cylindrical3Dfwd.h"
#include "Math/GenVector/Cylindrical3D.h"
#include "Math/GenVector/CylindricalEta3Dfwd.h"
#include "Math/GenVector/CylindricalEta3D.h"
#include "Math/GenVector/DisplacementVector2Dfwd.h"
#include "Math/GenVector/DisplacementVector2D.h"
#include "Math/GenVector/DisplacementVector3Dfwd.h"
#include "Math/GenVector/DisplacementVector3D.h"
#include "Math/GenVector/eta.h"
#include "Math/GenVector/etaMax.h"
#include "Math/GenVector/EulerAnglesfwd.h"
#include "Math/GenVector/EulerAngles.h"
#include "Math/GenVector/GenVector_exception.h"
#include "Math/GenVector/GenVectorIO.h"
#include "Math/GenVector/LorentzRotationfwd.h"
#include "Math/GenVector/LorentzRotation.h"
#include "Math/GenVector/LorentzVectorfwd.h"
#include "Math/GenVector/LorentzVector.h"
#include "Math/GenVector/Plane3D.h"
#include "Math/GenVector/Polar2Dfwd.h"
#include "Math/GenVector/Polar2D.h"
#include "Math/GenVector/Polar3Dfwd.h"
#include "Math/GenVector/Polar3D.h"
#include "Math/GenVector/PositionVector2Dfwd.h"
#include "Math/GenVector/PositionVector2D.h"
#include "Math/GenVector/PositionVector3Dfwd.h"
#include "Math/GenVector/PositionVector3D.h"
#include "Math/GenVector/PtEtaPhiE4Dfwd.h"
#include "Math/GenVector/PtEtaPhiE4D.h"
#include "Math/GenVector/PtEtaPhiM4Dfwd.h"
#include "Math/GenVector/PtEtaPhiM4D.h"
#include "Math/GenVector/PxPyPzE4Dfwd.h"
#include "Math/GenVector/PxPyPzE4D.h"
#include "Math/GenVector/PxPyPzM4Dfwd.h"
#include "Math/GenVector/PxPyPzM4D.h"
#include "Math/GenVector/Quaternionfwd.h"
#include "Math/GenVector/Quaternion.h"
#include "Math/GenVector/Rotation3Dfwd.h"
#include "Math/GenVector/Rotation3D.h"
#include "Math/GenVector/RotationXfwd.h"
#include "Math/GenVector/RotationX.h"
#include "Math/GenVector/RotationYfwd.h"
#include "Math/GenVector/RotationY.h"
#include "Math/GenVector/RotationZfwd.h"
#include "Math/GenVector/RotationZ.h"
#include "Math/GenVector/RotationZYXfwd.h"
#include "Math/GenVector/RotationZYX.h"
#include "Math/GenVector/Transform3D.h"
#include "Math/GenVector/Translation3D.h"
#include "Math/GenVector/VectorUtil.h"
#include "Math/LorentzRotation.h"
#include "Math/LorentzVector.h"
#include "Math/Plane3D.h"
#include "Math/Point2Dfwd.h"
#include "Math/Point2D.h"
#include "Math/Point3Dfwd.h"
#include "Math/Point3D.h"
#include "Math/Polar2D.h"
#include "Math/Polar3D.h"
#include "Math/PositionVector2D.h"
#include "Math/PositionVector3D.h"
#include "Math/PtEtaPhiE4D.h"
#include "Math/PtEtaPhiM4D.h"
#include "Math/PxPyPzE4D.h"
#include "Math/PxPyPzM4D.h"
#include "Math/Quaternion.h"
#include "Math/Rotation3D.h"
#include "Math/RotationX.h"
#include "Math/RotationY.h"
#include "Math/RotationZ.h"
#include "Math/RotationZYX.h"
#include "Math/Transform3D.h"
#include "Math/Translation3D.h"
#include "Math/Vector2Dfwd.h"
#include "Math/Vector2D.h"
#include "Math/Vector3Dfwd.h"
#include "Math/Vector3D.h"
#include "Math/Vector4Dfwd.h"
#include "Math/Vector4D.h"
#include "Math/VectorUtil.h"
// ./math/genvector/G__GenVector32.cxx
#include "Math/Point2D.h"
#include "Math/Point3D.h"
#include "Math/Vector2D.h"
#include "Math/Vector3D.h"
#include "Math/Vector4D.h"
// ./math/physics/G__Physics.cxx
#include "TFeldmanCousins.h"
#include "TGenPhaseSpace.h"
#include "TLorentzRotation.h"
#include "TLorentzVector.h"
#include "TQuaternion.h"
#include "TRobustEstimator.h"
#include "TRolke.h"
#include "TRotation.h"
#include "TVector2.h"
#include "TVector3.h"
// ./math/minuit/G__Minuit.cxx
#include "TFitter.h"
#include "TLinearFitter.h"
#include "TLinearMinimizer.h"
#include "TMinuit.h"
#include "TMinuitMinimizer.h"
// ./math/vecops/G__ROOTVecOps.cxx
#include "ROOT/RVec.hxx"
// ./core/G__Core.cxx
#include "ROOT/TErrorDefaultHandler.hxx"
#include "ROOT/TSequentialExecutor.hxx"
#include "ROOT/StringConv.hxx"
#include "Buttons.h"
#include "Bytes.h"
#include "Byteswap.h"
#include "KeySymbols.h"
#include "MessageTypes.h"
#include "Riostream.h"
#include "Rtypes.h"
#include "TApplication.h"
#include "TAtt3D.h"
#include "TAttAxis.h"
#include "TAttBBox2D.h"
#include "TAttBBox.h"
#include "TAttFill.h"
#include "TAttLine.h"
#include "TAttMarker.h"
#include "TAttPad.h"
#include "TAttText.h"
#include "TBase64.h"
#include "TBenchmark.h"
#include "TBuffer3D.h"
#include "TBuffer3DTypes.h"
#include "TBuffer.h"
#include "TColor.h"
#include "TColorGradient.h"
#include "TDatime.h"
#include "TDirectory.h"
#include "TEnv.h"
#include "TException.h"
#include "TExec.h"
#include "TFileCollection.h"
#include "TFileInfo.h"
#include "TFolder.h"
#include "TInetAddress.h"
#include "TMacro.h"
#include "TMathBase.h"
#include "TMD5.h"
#include "TMemberInspector.h"
#include "TMessageHandler.h"
#include "TNamed.h"
#include "TNotifyLink.h"
#include "TObject.h"
#include "TObjString.h"
#include "TParameter.h"
#include "TPluginManager.h"
#include "TPoint.h"
#include "TPRegexp.h"
#include "TProcessID.h"
#include "TProcessUUID.h"
#include "TQClass.h"
#include "TQCommand.h"
#include "TQConnection.h"
#include "TQObject.h"
#include "TRedirectOutputGuard.h"
#include "TRefCnt.h"
#include "TRef.h"
#include "TRegexp.h"
#include "TRemoteObject.h"
#include "TROOT.h"
#include "TRootIOCtor.h"
#include "TStopwatch.h"
#include "TStorage.h"
#include "TString.h"
#include "TStringLong.h"
#include "TStyle.h"
#include "TSysEvtHandler.h"
#include "TSystemDirectory.h"
#include "TSystemFile.h"
#include "TSystem.h"
#include "TTask.h"
#include "TThreadSlots.h"
#include "TTime.h"
#include "TTimer.h"
#include "TTimeStamp.h"
#include "TUri.h"
#include "TUrl.h"
#include "TUUID.h"
#include "TVersionCheck.h"
#include "TVirtualAuth.h"
#include "TVirtualFFT.h"
#include "TVirtualGL.h"
#include "TVirtualMonitoring.h"
#include "TVirtualMutex.h"
#include "TVirtualPadEditor.h"
#include "TVirtualPad.h"
#include "TVirtualPadPainter.h"
#include "TVirtualPerfStats.h"
#include "TVirtualPS.h"
#include "TVirtualQConnection.h"
#include "TVirtualRWMutex.h"
#include "TVirtualTableInterface.h"
#include "TVirtualViewer3D.h"
#include "TVirtualX.h"
#include "strlcpy.h"
#include "snprintf.h"
#include "strtok.h"
#include "ROOT/TSeq.hxx"
#include "TArrayC.h"
#include "TArrayD.h"
#include "TArrayF.h"
#include "TArray.h"
#include "TArrayI.h"
#include "TArrayL64.h"
#include "TArrayL.h"
#include "TArrayS.h"
#include "TBits.h"
#include "TBtree.h"
#include "TClassTable.h"
#include "TClonesArray.h"
#include "TCollection.h"
#include "TCollectionProxyInfo.h"
#include "TExMap.h"
#include "THashList.h"
#include "THashTable.h"
#include "TIterator.h"
#include "TList.h"
#include "TMap.h"
#include "TObjArray.h"
#include "TObjectTable.h"
#include "TOrdCollection.h"
#include "TRefArray.h"
#include "TRefTable.h"
#include "TSeqCollection.h"
#include "TSortedList.h"
#include "TVirtualCollectionProxy.h"
#include "ESTLType.h"
#include "RStringView.h"
#include "TClassEdit.h"
#include "TError.h"
#include "ROOT/RLogger.hxx"
#include "ROOT/RNotFn.hxx"
#include "ROOT/RRangeCast.hxx"
#include "ROOT/RSpan.hxx"
#include "ROOT/RStringView.hxx"
#include "ROOT/StringUtils.hxx"
#include "ROOT/span.hxx"
#include "ROOT/TypeTraits.hxx"
#include "TUnixSystem.h"
#include "root_std_complex.h"
#include "GuiTypes.h"
#include "TApplicationImp.h"
#include "TBrowser.h"
#include "TBrowserImp.h"
#include "TCanvasImp.h"
#include "TClassMenuItem.h"
#include "TContextMenu.h"
#include "TContextMenuImp.h"
#include "TControlBarImp.h"
#include "TGuiFactory.h"
#include "TInspectorImp.h"
#include "TObjectSpy.h"
#include "TToggleGroup.h"
#include "TToggle.h"
#include "TBaseClass.h"
#include "TClassGenerator.h"
#include "TClass.h"
#include "TClassRef.h"
#include "TClassStreamer.h"
#include "TDataMember.h"
#include "TDataType.h"
#include "TDictAttributeMap.h"
#include "TDictionary.h"
#include "TEnumConstant.h"
#include "TEnum.h"
#include "TFileMergeInfo.h"
#include "TFunction.h"
#include "TFunctionTemplate.h"
#include "TGenericClassInfo.h"
#include "TGlobal.h"
#include "TInterpreter.h"
#include "TInterpreterValue.h"
#include "TIsAProxy.h"
#include "TListOfDataMembers.h"
#include "TListOfEnums.h"
#include "TListOfEnumsWithLock.h"
#include "TListOfFunctions.h"
#include "TListOfFunctionTemplates.h"
#include "TMemberStreamer.h"
#include "TMethodArg.h"
#include "TMethodCall.h"
#include "TMethod.h"
#include "TProtoClass.h"
#include "TRealData.h"
#include "TSchemaHelper.h"
#include "TSchemaRule.h"
#include "TSchemaRuleSet.h"
#include "TStatusBitsChecker.h"
#include "TStreamerElement.h"
#include "TStreamer.h"
#include "TVirtualIsAProxy.h"
#include "TVirtualRefProxy.h"
#include "TVirtualStreamerInfo.h"
#include "TVirtualArray.h"
#include "TVirtualObject.h"
#include "Getline.h"
// Extra headers
#include "ROOT/TSeq.hxx"
#include "ROOT/StringConv.hxx"
